<a href="https://colab.research.google.com/github/kimetsu23/Nominas_Regresion/blob/main/Nominas_Regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAS NOMINAS BRUTAS RECOPILADAS CORRESPONDEN A:

- Direccion General De Aduanas: *Aduanas_Nomina*
- Minsterio De Agricultura: *Agricultura_Nomina*
- Direccion General De Impuestos Internos (DGII): *ImpuestosInternos_Nomina*
- Minsterio De Medio Ambiente Y Recursos Naturales: *MedioAmbiente_Nomina*
- Ministerio De Obras Publicas Y Comunicaciones: *ObrasPublicas_Nomina*

In [ ]:
import pandas as pd
import numpy as np
import datetime
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
DF_Nomina_Agricultura_Bruta = pd.read_csv("Agricultura_Nomina.csv")

In [ ]:
DF_Nomina_Agricultura_Bruta

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,BASE TODAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Correspondiente al mes de Octubre del año 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No.,Nombres,Apellidos,Cargo,Lugar Funciones,Tipo Empleado,CARRERA ADMVA,Sueldo Bruto,AFP,ISR,Seguro Familiar Salud,SFS Salud Padres,Seguro Vida INAVI,Serv. Funerarios INAVI,Fund. Dom. Cred. Educ.,Otros Descuentos,Total Descuentos,Ingreso Neto,Genero
3,1,LIMBER LUCAS,CRUZ LOPEZ,MINISTRO (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 300,000.00","$ 8,610.00","$ 59,783.08","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 75,007.22","$ 224,992.78",MASCULINO
4,2,DARIO ARCIDE,VARGAS MENA,VICEMINISTRO (A),VICEMINISTERIO DE EXTENSION Y CAPACITACION AGR...,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 61,430.97","$ 188,569.03",MASCULINO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7800,3271,MIGUEL ANTONIO,GUZMAN PEREZ,SEGURIDAD,DIVISION DE SEGURIDAD,PERSONAL DE VIGILANCIA,NaN,"$ 4,000.00",0,0,0,0,0,0,NaN,0,0,"$ 4,000.00",MASCULINO
7801,3271,JOSE LUIS,PEÑA,SEGURIDAD,DIVISION DE SEGURIDAD,PERSONAL DE VIGILANCIA,NaN,"$ 1,000.00",0,0,0,0,0,0,NaN,0,0,"$ 1,000.00",MASCULINO
7802,3271,MICHAEL MIGUEL,FRIAS PEÑA,SEGURIDAD,DIVISION DE SEGURIDAD,PERSONAL DE VIGILANCIA,NaN,"$ 1,000.00",0,0,0,0,0,0,NaN,0,0,"$ 1,000.00",MASCULINO
7803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$ 240,323,746.16",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_Agricultura_Bruta.head(51)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,BASE TODAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Correspondiente al mes de Octubre del año 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No.,Nombres,Apellidos,Cargo,Lugar Funciones,Tipo Empleado,CARRERA ADMVA,Sueldo Bruto,AFP,ISR,Seguro Familiar Salud,SFS Salud Padres,Seguro Vida INAVI,Serv. Funerarios INAVI,Fund. Dom. Cred. Educ.,Otros Descuentos,Total Descuentos,Ingreso Neto,Genero
3,1,LIMBER LUCAS,CRUZ LOPEZ,MINISTRO (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 300,000.00","$ 8,610.00","$ 59,783.08","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 75,007.22","$ 224,992.78",MASCULINO
4,2,DARIO ARCIDE,VARGAS MENA,VICEMINISTRO (A),VICEMINISTERIO DE EXTENSION Y CAPACITACION AGR...,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 61,430.97","$ 188,569.03",MASCULINO
5,3,EULALIO,RAMIREZ RAMIREZ,VICEMINISTRO (A),VICEMINISTERIO DE PRODUCCION AGRICOLA Y MERCADEO,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,$ 900.00,"$ 62,330.97","$ 187,669.03",MASCULINO
6,4,FARUK,GARIB ARBAJE,ASESOR,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,"$ 6,300.00","$ 67,730.97","$ 182,269.03",MASCULINO
7,5,FREDY RAMON,FERNANDEZ ACOSTA,DIRECTOR (A) DE GABINETE,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 61,430.97","$ 188,569.03",MASCULINO
8,6,JOSE RAFAEL,PAULINO RODRIGUEZ,VICEMINISTRO PLANIFICACION,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 61,430.97","$ 188,569.03",MASCULINO
9,7,MIRIAN ESTELA,GUZMAN TEJADA,VICEMINISTRO (A),VICEMINISTERIO DE DESARROLLO RURAL- MA,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,"$ 3,821.30","$ 65,252.27","$ 184,747.73",FEMENINO
10,8,RAFAEL ANTONIO,ORTIZ QUEZADA,VICEMINISTRO (A),VICEMINISTERIO DE ASUNTOS CIENTIFICOS Y TECNOL...,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,"$ 14,912.39","$ 76,343.36","$ 173,656.64",MASCULINO
11,9,RAMON FERNANDO,JAQUEZ GARCIA,VICEMINISTRO (A) ADMINISTRATIVO (A),VICEMINISTERIO ADMINISTRATIVO FINANCIERO- MA,FIJO,NaN,"$ 250,000.00","$ 7,175.00","$ 47,641.83","$ 6,589.14",0,$ 25.00,0,NaN,0,"$ 61,430.97","$ 188,569.03",MASCULINO
12,10,LEONARDO ANTONIO,FAÑA BATISTA,DIRECTOR (A),MINISTERIO DE AGRICULTURA,EMPLEADOS TEMPORALES,NaN,"$ 200,000.00","$ 5,740.00","$ 35,627.87","$ 6,080.00",0,$ 25.00,0,NaN,"$ 10,525.00","$ 57,997.87","$ 142,002.13",MASCULINO
13,11,EDUARDO ANTONIO,MERCEDES SANCHEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 180,000.00","$ 5,166.00","$ 30,494.50","$ 5,472.00","$ 1,715.46",$ 25.00,0,NaN,"$ 1,325.00","$ 44,197.96","$ 135,802.04",MASCULINO
14,12,FAUSTO ELIAS,TEJADA GUZMAN,ASESOR,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 180,000.00","$ 5,166.00","$ 30,923.37","$ 5,472.00",0,$ 25.00,0,NaN,"$ 63,090.87","$ 104,677.24","$ 75,322.76",MASCULINO
15,12,FRANK MARTIN,VENTURA BETANCES,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORDESTE-MA,EMPLEADOS TEMPORALES,NaN,"$ 180,000.00","$ 5,166.00","$ 30,065.64","$ 5,472.00","$ 3,430.92",$ 25.00,0,NaN,"$ 1,800.00","$ 45,959.56","$ 134,040.44",MASCULINO
16,12,GREGORIO M.,DE LOS SANTOS,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA SUR- MA,FIJO,CARRERA ADMINISTRATIVA,"$ 180,000.00","$ 5,166.00","$ 30,923.37","$ 5,472.00",0,$ 25.00,0,NaN,"$ 10,100.00","$ 51,686.37","$ 128,313.63",MASCULINO
17,12,JUAN BAUTISTA,MATEO VALDEZ,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA SUROESTE- MA,EMPLEADOS TEMPORALES,NaN,"$ 180,000.00","$ 5,166.00","$ 30,923.37","$ 5,472.00",0,$ 25.00,0,NaN,"$ 4,200.00","$ 45,786.37","$ 134,213.63",MASCULINO
18,12,PABLO REINALDO,DE MOYA MORAN,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORCENTRAL- MA,EMPLEADOS TEMPORALES,NaN,"$ 180,000.00","$ 5,166.00","$ 30,923.37","$ 5,472.00",0,$ 25.00,0,NaN,0,"$ 41,586.37","$ 138,413.63",MASCULINO
19,12,PEDRO,TRINIDAD LEDESMA,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORTE- MA,EMPLEADOS TEMPORALES,NaN,"$ 180,000.00","$ 5,166.00","$ 30,923.37","$ 5,472.00",0,$ 25.00,0,NaN,"$ 8,100.00","$ 49,686.37","$ 130,313.63",MASCULINO
20,12,RAFAEL ERNESTO,SOTO SOTO,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA CENTRAL- MA,EMPLEADOS TEMPORALES,NaN,"$ 180,000.00","$ 5,166.00","$ 30,923.37","$ 5,472.00",0,$ 25.00,0,NaN,0,"$ 41,586.37","$ 138,413.63",MASCULINO
21,13,LUIS ERNESTO,PEREZ CUEVAS,ASESOR,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 175,000.00","$ 5,022.50","$ 29,747.24","$ 5,320.00",0,$ 25.00,0,NaN,0,"$ 40,114.74","$ 134,885.26",MASCULINO
22,14,PABLO ANTONIO,RODRIGUEZ NUÑEZ,ASESOR,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 175,000.00","$ 5,022.50","$ 29,747.24","$ 5,320.00",0,$ 25.00,0,NaN,"$ 6,300.00","$ 46,414.74","$ 128,585.26",MASCULINO
23,15,YOHAN MANUEL,LOPEZ DILONE,ASESOR (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 175,000.00","$ 5,022.50","$ 29,747.24","$ 5,320.00",0,$ 25.00,0,NaN,"$ 3,771.30","$ 43,886.04","$ 131,113.96",MASCULINO
24,16,GUSTAVO GUILLERMO DE JESUS,GOMEZ THORMANN,DIRECTOR (A),DIRECCION ADMINISTRATIVA,EMPLEADOS TEMPORALES,NaN,"$ 170,000.00","$ 4,879.00","$ 28,571.12","$ 5,168.00",0,$ 25.00,0,NaN,0,"$ 38,643.12","$ 131,356.88",MASCULINO
25,17,PEDRO CARLOS,VERAS TAVAREZ,DIRECTOR FINANCIERO,DEPARTAMENTO FINANCIERO,EMPLEADOS TEMPORALES,NaN,"$ 170,000.00","$ 4,879.00","$ 28,571.12","$ 5,168.00",0,$ 25.00,0,NaN,0,"$ 38,643.12","$ 131,356.88",MASCULINO
26,18,ALBA KARINA,SUAREZ SANTOS,DIRECTOR (A),DEPARTAMENTO DE ANALISIS Y GESTION OPERATIVA- MA,EMPLEADOS TEMPORALES,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,0,"$ 32,756.62","$ 117,243.38",FEMENINO
27,19,ANGEL,FELIZ JIMENEZ,ENCARGADO DE DEPARTAMENTO,DIRECCION DE FOMENTO Y PRODUCCION AGRICOLA,EMPLEADOS TEMPORALES,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,"$ 60,853.42","$ 93,610.04","$ 56,389.96",MASCULINO
28,20,CESAR SANDINO,DE JESUS REINOSO,SECRETARIO EJECUTIVO,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,$ 50.00,"$ 32,806.62","$ 117,193.38",MASCULINO
29,20,CRISTOBAL OSVALDO,GUERRERO CEDEÑO,DIRECTOR (A),DIRECCION REGIONAL AGROPECUARIA ESTE- MA,EMPLEADOS TEMPORALES,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,"$ 5,028.40","$ 37,785.02","$ 112,214.98",MASCULINO
30,21,ERNESTO MANUEL,DE MOYA SANCHEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,0,"$ 32,756.62","$ 117,243.38",MASCULINO
31,22,JUAN RAMON,ROMNEY MORENO,ASISTENTE,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,0,"$ 32,756.62","$ 117,243.38",MASCULINO
32,23,LIDIA MARLENE,JONES CASTRO,COORDINADOR GENERAL,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,0,$ 50.00,"$ 32,806.62","$ 117,193.38",FEMENINO
33,24,LUCHY,GUZMAN GERMAN DE MAYOL,ENCARGADO (A),DEPARTAMENTO DE DESARROLLO INSTITUCIONAL Y CAL...,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,0,"$ 32,756.62","$ 117,243.38",FEMENINO
34,25,MANUEL EMILIO,GONZALEZ TEJERA,ASESOR,DEPARTAMENTO DE ECONOMIA AGROPECUARIA Y ESTADI...,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,"$ 4,600.00","$ 37,356.62","$ 112,643.38",MASCULINO
35,26,MARILEIDY,DE LA CRUZ CONCEPCION,COORDINADOR GENERAL,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,0,"$ 32,756.62","$ 117,243.38",FEMENINO
36,26,NELY ROBER,RODRIGUEZ GOMEZ,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NOROESTE- MA,EMPLEADOS TEMPORALES,NaN,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,"$ 19,670.76","$ 52,427.38","$ 97,572.62",MASCULINO
37,27,ROSA MARIA,LAZALA ABREU,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE SANIDAD VEGETAL- MA,FIJO,CARRERA ADMINISTRATIVA,"$ 150,000.00","$ 4,305.00","$ 23,866.62","$ 4,560.00",0,$ 25.00,0,NaN,"$ 58,223.77","$ 90,980.39","$ 59,019.61",FEMENINO
38,28,CARLIXTO,TAPIA VILORIA,DIRECTOR (A),LABORATORIO DE MICROPROPAGACION DE PLANTAS IN ...,EMPLEADOS TEMPORALES,NaN,"$ 145,000.00","$ 4,161.50","$ 22,261.63","$ 4,408.00","$ 1,715.46",$ 25.00,0,NaN,"$ 2,437.50","$ 35,009.09","$ 109,990.91",MASCULINO
39,29,JOSE RAFAEL,ESCARRAMAN HERNANDEZ,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE PRODUCCION BAJO AMBIENTE PROTE...,EMPLEADOS TEMPORALES,NaN,"$ 145,000.00","$ 4,161.50","$ 22,261.63","$ 4,408.00","$ 1,715.46",$ 25.00,0,NaN,$ 750.00,"$ 33,321.59","$ 111,678.41",MASCULINO
40,30,MARCELINO ANTONIO,VARGAS VARGAS,ASISTENTE ESPECIAL DEL MINISTRO,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 145,000.00","$ 4,161.50","$ 22,690.49","$ 4,408.00",0,$ 25.00,0,NaN,0,"$ 31,284.99","$ 113,715.01",MASCULINO
41,31,YENIRSE ADAIRYS,TEJEDA VILLAR,ASISTENTE,MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 145,000.00","$ 4,161.50","$ 22,690.49","$ 4,408.00",0,$ 25.00,0,NaN,0,"$ 31,284.99","$ 113,715.01",FEMENINO
42,32,LUISA JANELY,PEREZ VALENTIN,DIRECTOR (A) PLANIFICACION Y DESARROLLO,DIRECCION DE PLANIFICACION Y DESARROLLO,FIJO,CARRERA ADMINISTRATIVA,"$ 140,000.00","$ 4,018.00","$ 21,085.50","$ 4,256.00","$ 1,715.46",$ 25.00,$ 100.00,NaN,"$ 1,225.00","$ 32,424.96","$ 107,575.04",FEMENINO
43,33,DAURY,CEDEÑO HOLGUIN,COORDINADOR (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 135,000.00","$ 3,874.50","$ 20,338.24","$ 4,104.00",0,$ 25.00,0,NaN,0,"$ 28,341.74","$ 106,658.26",MASCULINO
44,34,YTALIA ALTAGRACIA,VASQUEZ DE DIAZ,DIRECTOR (A) RECURSOS HUMANOS,DIRECCION DE RECURSOS HUMANOS- MA,EMPLEADOS TEMPORALES,NaN,"$ 135,000.00","$ 3,874.50","$ 20,338.24","$ 4,104.00",0,$ 25.00,0,NaN,"$ 2,100.00","$ 30,441.74","$ 104,558.26",FEMENINO
45,35,BETHANIA MIGUELINA,RODRIGUEZ ALVAREZ,COORDINADOR (A),DEPARTAMENTO DE PERMISOS DE IMPORTACION DE PRO...,FIJO,NaN,"$ 130,000.00","$ 3,731.00","$ 18,733.25","$ 3,952.00","$ 1,715.46",$ 25.00,0,NaN,"$ 22,190.00","$ 50,346.71","$ 79,653.29",FEMENINO
46,36,DANILO,ABREU NUÑEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,FIJO,NaN,"$ 130,000.00","$ 3,731.00","$ 19,162.12","$ 3,952.00",0,$ 25.00,0,NaN,0,"$ 26,870.12","$ 103,129.88",MASCULINO
47,37,BRENDA NATACHA,JIMENEZ CANDELARIO,ANALISTA DE COMPRAS Y CONTRATACIONES,DEPARTAMENTO DE COMPRAS Y CONTRATACIONES,FIJO,CARRERA ADMINISTRATIVA,"$ 125,000.00","$ 3,587.50","$ 17,557.13","$ 3,800.00","$ 1,715.46",$ 25.00,0,0,"$ 2,100.00","$ 28,785.09","$ 96,214.91",FEMENINO
48,38,EDGAR ARNALDO,PEREZ TAVERAS,ENCARGADO(A) DEPARTAMENTO,DEPARTAMENTO DE TRANSPORTACION,EMPLEADOS TEMPORALES,NaN,"$ 125,000.00","$ 3,587.50","$ 17,985.99","$ 3,800.00",0,$ 25.00,0,NaN,0,"$ 25,398.49","$ 99,601.51",MASCULINO
49,39,ELADIA OLIVA,BELTRE DIAZ,ENC. DPTO. TESORERIA,DEPARTAMENTO DE TESORERIA,EMPLEADOS TEMPORALES,NaN,"$ 125,000.00","$ 3,587.50","$ 17,985.99","$ 3,800.00",0,$ 25.00,0,NaN,0,"$ 25,398.49","$ 99,601.51",FEMENINO
50,40,FIORDANNA,DE LA MAZA BENCOSME,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE ACCESO A LA INFORMACION- MA,EMPLEADOS TEMPORALES,NaN,"$ 125,000.00","$ 3,587.50","$ 17,985.99","$ 3,800.00",0,$ 25.00,0,NaN,$ 50.00,"$ 25,448.49","$ 99,551.51",FEMENINO

In [ ]:
DF_Nomina_Agricultura_Bruta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7805 entries, 0 to 7804
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   7803 non-null   object
 1   Unnamed: 1   7801 non-null   object
 2   Unnamed: 2   7801 non-null   object
 3   Unnamed: 3   7801 non-null   object
 4   Unnamed: 4   7801 non-null   object
 5   Unnamed: 5   7801 non-null   object
 6   Unnamed: 6   1728 non-null   object
 7   Unnamed: 7   7802 non-null   object
 8   Unnamed: 8   7801 non-null   object
 9   Unnamed: 9   7801 non-null   object
 10  Unnamed: 10  7801 non-null   object
 11  Unnamed: 11  7801 non-null   object
 12  Unnamed: 12  7801 non-null   object
 13  Unnamed: 13  7801 non-null   object
 14  Unnamed: 14  81 non-null     object
 15  Unnamed: 15  7801 non-null   object
 16  Unnamed: 16  7801 non-null   object
 17  Unnamed: 17  7801 non-null   object
 18  Unnamed: 18  7801 non-null   object
dtypes: object(19)
memory usage: 1.1+ MB

In [ ]:
# Copia TODO esto en una celda y ejecuta:
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_Bruta.copy()


# 1. Renombrar columnas necesarias
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA.rename(columns={
    'Unnamed: 1': 'Nombres',
    'Unnamed: 2': 'Apellidos',
    'Unnamed: 3': 'Cargo_Funcion',
    'Unnamed: 4': 'Locacion_Departamento',
    'Unnamed: 7': 'Salario_Bruto',
    'Unnamed: 8': 'Descuento_AFP',
    'Unnamed: 9': 'Descuento_ISR',
    'Unnamed: 10': 'Descuento_SFS',
    'Unnamed: 16': 'Total_Descuentos',
    'Unnamed: 17': 'Salario_Neto'
})


# 2. Crear UNA SOLA columna con nombre y apellido combinados
DF_Nomina_Agricultura_NETA['Nombre_Completo'] = DF_Nomina_Agricultura_NETA['Nombres'] + ' ' + DF_Nomina_Agricultura_NETA['Apellidos']


# 3. Crear columna de otros descuentos (ya como números)
# NOTA: Añadimos 'r' antes de las comillas para raw strings
DF_Nomina_Agricultura_NETA['Otros_Descuentos'] = (
    pd.to_numeric(DF_Nomina_Agricultura_NETA['Unnamed: 11'].replace(r'[\$,]', '', regex=True), errors='coerce').fillna(0) +
    pd.to_numeric(DF_Nomina_Agricultura_NETA['Unnamed: 12'].replace(r'[\$,]', '', regex=True), errors='coerce').fillna(0) +
    pd.to_numeric(DF_Nomina_Agricultura_NETA['Unnamed: 13'].replace(r'[\$,]', '', regex=True), errors='coerce').fillna(0) +
    pd.to_numeric(DF_Nomina_Agricultura_NETA['Unnamed: 15'].replace(r'[\$,]', '', regex=True), errors='coerce').fillna(0)
)


# 4. LIMPIAR Y CONVERTIR TODAS LAS COLUMNAS NUMÉRICAS
# Quitar símbolos $ y comas, convertir a números
columnas_numericas = [
    'Salario_Bruto',
    'Descuento_AFP',
    'Descuento_ISR',
    'Descuento_SFS',
    'Total_Descuentos',
    'Salario_Neto'
]


for col in columnas_numericas:
    DF_Nomina_Agricultura_NETA[col] = pd.to_numeric(
        DF_Nomina_Agricultura_NETA[col].astype(str).replace(r'[\$,]', '', regex=True),
        errors='coerce'
    )


# 5. Seleccionar SOLO las 11 columnas finales
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA[[
    'Nombre_Completo',
    'Cargo_Funcion',
    'Locacion_Departamento',
    'Salario_Bruto',
    'Descuento_AFP',
    'Descuento_ISR',
    'Descuento_SFS',
    'Otros_Descuentos',
    'Total_Descuentos',  # ← Ahora será un número limpio
    'Salario_Neto'
]]

In [ ]:
DF_Nomina_Agricultura_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,Nombres Apellidos,Cargo,Lugar Funciones,NaN,NaN,NaN,NaN,0.0,NaN,NaN
3,LIMBER LUCAS CRUZ LOPEZ,MINISTRO (A),MINISTERIO DE AGRICULTURA,3.000000e+05,8610.0,59783.08,6589.14,25.0,75007.22,224992.78
4,DARIO ARCIDE VARGAS MENA,VICEMINISTRO (A),VICEMINISTERIO DE EXTENSION Y CAPACITACION AGR...,2.500000e+05,7175.0,47641.83,6589.14,25.0,61430.97,188569.03
...,...,...,...,...,...,...,...,...,...,...
7800,MIGUEL ANTONIO GUZMAN PEREZ,SEGURIDAD,DIVISION DE SEGURIDAD,4.000000e+03,0.0,0.00,0.00,0.0,0.00,4000.00
7801,JOSE LUIS PEÑA,SEGURIDAD,DIVISION DE SEGURIDAD,1.000000e+03,0.0,0.00,0.00,0.0,0.00,1000.00
7802,MICHAEL MIGUEL FRIAS PEÑA,SEGURIDAD,DIVISION DE SEGURIDAD,1.000000e+03,0.0,0.00,0.00,0.0,0.00,1000.00
7803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
7804,NaN,NaN,NaN,2.403237e+08,NaN,NaN,NaN,0.0,NaN,NaN

In [ ]:
DF_Nomina_Agricultura_NETA.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN
2,Nombres Apellidos,Cargo,Lugar Funciones,NaN,NaN,NaN,NaN,0.00,NaN,NaN
3,LIMBER LUCAS CRUZ LOPEZ,MINISTRO (A),MINISTERIO DE AGRICULTURA,300000.0,8610.0,59783.08,6589.14,25.00,75007.22,224992.78
4,DARIO ARCIDE VARGAS MENA,VICEMINISTRO (A),VICEMINISTERIO DE EXTENSION Y CAPACITACION AGR...,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
5,EULALIO RAMIREZ RAMIREZ,VICEMINISTRO (A),VICEMINISTERIO DE PRODUCCION AGRICOLA Y MERCADEO,250000.0,7175.0,47641.83,6589.14,925.00,62330.97,187669.03
6,FARUK GARIB ARBAJE,ASESOR,MINISTERIO DE AGRICULTURA,250000.0,7175.0,47641.83,6589.14,6325.00,67730.97,182269.03
7,FREDY RAMON FERNANDEZ ACOSTA,DIRECTOR (A) DE GABINETE,MINISTERIO DE AGRICULTURA,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
8,JOSE RAFAEL PAULINO RODRIGUEZ,VICEMINISTRO PLANIFICACION,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
9,MIRIAN ESTELA GUZMAN TEJADA,VICEMINISTRO (A),VICEMINISTERIO DE DESARROLLO RURAL- MA,250000.0,7175.0,47641.83,6589.14,3846.30,65252.27,184747.73
10,RAFAEL ANTONIO ORTIZ QUEZADA,VICEMINISTRO (A),VICEMINISTERIO DE ASUNTOS CIENTIFICOS Y TECNOL...,250000.0,7175.0,47641.83,6589.14,14937.39,76343.36,173656.64
11,RAMON FERNANDO JAQUEZ GARCIA,VICEMINISTRO (A) ADMINISTRATIVO (A),VICEMINISTERIO ADMINISTRATIVO FINANCIERO- MA,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
12,LEONARDO ANTONIO FAÑA BATISTA,DIRECTOR (A),MINISTERIO DE AGRICULTURA,200000.0,5740.0,35627.87,6080.00,10550.00,57997.87,142002.13
13,EDUARDO ANTONIO MERCEDES SANCHEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,180000.0,5166.0,30494.50,5472.00,3065.46,44197.96,135802.04
14,FAUSTO ELIAS TEJADA GUZMAN,ASESOR,MINISTERIO DE AGRICULTURA,180000.0,5166.0,30923.37,5472.00,63115.87,104677.24,75322.76
15,FRANK MARTIN VENTURA BETANCES,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORDESTE-MA,180000.0,5166.0,30065.64,5472.00,5255.92,45959.56,134040.44
16,GREGORIO M. DE LOS SANTOS,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA SUR- MA,180000.0,5166.0,30923.37,5472.00,10125.00,51686.37,128313.63
17,JUAN BAUTISTA MATEO VALDEZ,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA SUROESTE- MA,180000.0,5166.0,30923.37,5472.00,4225.00,45786.37,134213.63
18,PABLO REINALDO DE MOYA MORAN,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORCENTRAL- MA,180000.0,5166.0,30923.37,5472.00,25.00,41586.37,138413.63
19,PEDRO TRINIDAD LEDESMA,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORTE- MA,180000.0,5166.0,30923.37,5472.00,8125.00,49686.37,130313.63
20,RAFAEL ERNESTO SOTO SOTO,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA CENTRAL- MA,180000.0,5166.0,30923.37,5472.00,25.00,41586.37,138413.63
21,LUIS ERNESTO PEREZ CUEVAS,ASESOR,MINISTERIO DE AGRICULTURA,175000.0,5022.5,29747.24,5320.00,25.00,40114.74,134885.26
22,PABLO ANTONIO RODRIGUEZ NUÑEZ,ASESOR,MINISTERIO DE AGRICULTURA,175000.0,5022.5,29747.24,5320.00,6325.00,46414.74,128585.26
23,YOHAN MANUEL LOPEZ DILONE,ASESOR (A),MINISTERIO DE AGRICULTURA,175000.0,5022.5,29747.24,5320.00,3796.30,43886.04,131113.96
24,GUSTAVO GUILLERMO DE JESUS GOMEZ THORMANN,DIRECTOR (A),DIRECCION ADMINISTRATIVA,170000.0,4879.0,28571.12,5168.00,25.00,38643.12,131356.88
25,PEDRO CARLOS VERAS TAVAREZ,DIRECTOR FINANCIERO,DEPARTAMENTO FINANCIERO,170000.0,4879.0,28571.12,5168.00,25.00,38643.12,131356.88
26,ALBA KARINA SUAREZ SANTOS,DIRECTOR (A),DEPARTAMENTO DE ANALISIS Y GESTION OPERATIVA- MA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
27,ANGEL FELIZ JIMENEZ,ENCARGADO DE DEPARTAMENTO,DIRECCION DE FOMENTO Y PRODUCCION AGRICOLA,150000.0,4305.0,23866.62,4560.00,60878.42,93610.04,56389.96
28,CESAR SANDINO DE JESUS REINOSO,SECRETARIO EJECUTIVO,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,150000.0,4305.0,23866.62,4560.00,75.00,32806.62,117193.38
29,CRISTOBAL OSVALDO GUERRERO CEDEÑO,DIRECTOR (A),DIRECCION REGIONAL AGROPECUARIA ESTE- MA,150000.0,4305.0,23866.62,4560.00,5053.40,37785.02,112214.98
30,ERNESTO MANUEL DE MOYA SANCHEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
31,JUAN RAMON ROMNEY MORENO,ASISTENTE,MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
32,LIDIA MARLENE JONES CASTRO,COORDINADOR GENERAL,MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,75.00,32806.62,117193.38
33,LUCHY GUZMAN GERMAN DE MAYOL,ENCARGADO (A),DEPARTAMENTO DE DESARROLLO INSTITUCIONAL Y CAL...,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
34,MANUEL EMILIO GONZALEZ TEJERA,ASESOR,DEPARTAMENTO DE ECONOMIA AGROPECUARIA Y ESTADI...,150000.0,4305.0,23866.62,4560.00,4625.00,37356.62,112643.38
35,MARILEIDY DE LA CRUZ CONCEPCION,COORDINADOR GENERAL,MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
36,NELY ROBER RODRIGUEZ GOMEZ,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NOROESTE- MA,150000.0,4305.0,23866.62,4560.00,19695.76,52427.38,97572.62
37,ROSA MARIA LAZALA ABREU,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE SANIDAD VEGETAL- MA,150000.0,4305.0,23866.62,4560.00,58248.77,90980.39,59019.61
38,CARLIXTO TAPIA VILORIA,DIRECTOR (A),LABORATORIO DE MICROPROPAGACION DE PLANTAS IN ...,145000.0,4161.5,22261.63,4408.00,4177.96,35009.09,109990.91
39,JOSE RAFAEL ESCARRAMAN HERNANDEZ,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE PRODUCCION BAJO AMBIENTE PROTE...,145000.0,4161.5,22261.63,4408.00,2490.46,33321.59,111678.41
40,MARCELINO ANTONIO VARGAS VARGAS,ASISTENTE ESPECIAL DEL MINISTRO,MINISTERIO DE AGRICULTURA,145000.0,4161.5,22690.49,4408.00,25.00,31284.99,113715.01
41,YENIRSE ADAIRYS TEJEDA VILLAR,ASISTENTE,MINISTERIO DE AGRICULTURA,145000.0,4161.5,22690.49,4408.00,25.00,31284.99,113715.01
42,LUISA JANELY PEREZ VALENTIN,DIRECTOR (A) PLANIFICACION Y DESARROLLO,DIRECCION DE PLANIFICACION Y DESARROLLO,140000.0,4018.0,21085.50,4256.00,3065.46,32424.96,107575.04
43,DAURY CEDEÑO HOLGUIN,COORDINADOR (A),MINISTERIO DE AGRICULTURA,135000.0,3874.5,20338.24,4104.00,25.00,28341.74,106658.26
44,YTALIA ALTAGRACIA VASQUEZ DE DIAZ,DIRECTOR (A) RECURSOS HUMANOS,DIRECCION DE RECURSOS HUMANOS- MA,135000.0,3874.5,20338.24,4104.00,2125.00,30441.74,104558.26
45,BETHANIA MIGUELINA RODRIGUEZ ALVAREZ,COORDINADOR (A),DEPARTAMENTO DE PERMISOS DE IMPORTACION DE PRO...,130000.0,3731.0,18733.25,3952.00,23930.46,50346.71,79653.29
46,DANILO ABREU NUÑEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,130000.0,3731.0,19162.12,3952.00,25.00,26870.12,103129.88
47,BRENDA NATACHA JIMENEZ CANDELARIO,ANALISTA DE COMPRAS Y CONTRATACIONES,DEPARTAMENTO DE COMPRAS Y CONTRATACIONES,125000.0,3587.5,17557.13,3800.00,3840.46,28785.09,96214.91
48,EDGAR ARNALDO PEREZ TAVERAS,ENCARGADO(A) DEPARTAMENTO,DEPARTAMENTO DE TRANSPORTACION,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
49,ELADIA OLIVA BELTRE DIAZ,ENC. DPTO. TESORERIA,DEPARTAMENTO DE TESORERIA,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
50,FIORDANNA DE LA MAZA BENCOSME,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE ACCESO A LA INFORMACION- MA,125000.0,3587.5,17985.99,3800.00,75.00,25448.49,99551.51

In [ ]:
# 1. Eliminar específicamente la fila que tiene "Nombres Apellidos" en Nombre_Completo
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA[DF_Nomina_Agricultura_NETA['Nombre_Completo'] != 'Nombres Apellidos']

# 2. Eliminar líneas con cualquier valor NaN
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA.dropna(how='any')

# 3. Eliminar duplicados de 'Nombre_Completo' manteniendo el mayor Salario_Neto
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA.sort_values('Salario_Neto', ascending=False)
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA.drop_duplicates(subset=['Nombre_Completo'], keep='first')

# 4. Resetear índice
DF_Nomina_Agricultura_NETA = DF_Nomina_Agricultura_NETA.reset_index(drop=True)

In [ ]:
DF_Nomina_Agricultura_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,LIMBER LUCAS CRUZ LOPEZ,MINISTRO (A),MINISTERIO DE AGRICULTURA,300000.0,8610.00,59783.08,6589.14,25.00,75007.22,224992.78
1,FREDY RAMON FERNANDEZ ACOSTA,DIRECTOR (A) DE GABINETE,MINISTERIO DE AGRICULTURA,250000.0,7175.00,47641.83,6589.14,25.00,61430.97,188569.03
2,JOSE RAFAEL PAULINO RODRIGUEZ,VICEMINISTRO PLANIFICACION,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,250000.0,7175.00,47641.83,6589.14,25.00,61430.97,188569.03
3,DARIO ARCIDE VARGAS MENA,VICEMINISTRO (A),VICEMINISTERIO DE EXTENSION Y CAPACITACION AGR...,250000.0,7175.00,47641.83,6589.14,25.00,61430.97,188569.03
4,RAMON FERNANDO JAQUEZ GARCIA,VICEMINISTRO (A) ADMINISTRATIVO (A),VICEMINISTERIO ADMINISTRATIVO FINANCIERO- MA,250000.0,7175.00,47641.83,6589.14,25.00,61430.97,188569.03
...,...,...,...,...,...,...,...,...,...,...
7789,GEORGINA GARCIA MERCEDES,AUXILIAR,DEPARTAMENTO DE COMUNICACION E INFORMACION PAR...,25200.0,723.24,0.00,766.08,23690.68,25180.00,20.00
7790,FELIX ALVARADO GUZMAN MARTINEZ,TECNICO I,DIRECCION REGIONAL AGROPECUARIA SUROESTE- MA,50000.0,1435.00,1854.00,1520.00,45171.00,49980.00,20.00
7791,FRANCISCO ANTIGUA ROMERO,TECNICO I,DIRECCION REGIONAL AGROPECUARIA NORDESTE-MA,50000.0,1435.00,1596.68,1520.00,45428.32,49980.00,20.00
7792,GREGORIO MEDINA RUIZ,PROFESIONAL SUPERIOR III COORDINADOR,DEPARTAMENTO DE SANIDAD VEGETAL- MA,50000.0,1435.00,1854.00,1520.00,45171.00,49980.00,20.00
7793,JOHANGEL ENMANUEL MARTE MEREJO,OBRERO,DIRECCION REGIONAL AGROPECUARIA NORDESTE-MA,10000.0,287.00,0.00,304.00,9389.00,9980.00,20.00

In [ ]:
DF_Nomina_Agricultura_NETA.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,LIMBER LUCAS CRUZ LOPEZ,MINISTRO (A),MINISTERIO DE AGRICULTURA,300000.0,8610.0,59783.08,6589.14,25.00,75007.22,224992.78
1,FREDY RAMON FERNANDEZ ACOSTA,DIRECTOR (A) DE GABINETE,MINISTERIO DE AGRICULTURA,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
2,JOSE RAFAEL PAULINO RODRIGUEZ,VICEMINISTRO PLANIFICACION,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
3,DARIO ARCIDE VARGAS MENA,VICEMINISTRO (A),VICEMINISTERIO DE EXTENSION Y CAPACITACION AGR...,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
4,RAMON FERNANDO JAQUEZ GARCIA,VICEMINISTRO (A) ADMINISTRATIVO (A),VICEMINISTERIO ADMINISTRATIVO FINANCIERO- MA,250000.0,7175.0,47641.83,6589.14,25.00,61430.97,188569.03
5,EULALIO RAMIREZ RAMIREZ,VICEMINISTRO (A),VICEMINISTERIO DE PRODUCCION AGRICOLA Y MERCADEO,250000.0,7175.0,47641.83,6589.14,925.00,62330.97,187669.03
6,MIRIAN ESTELA GUZMAN TEJADA,VICEMINISTRO (A),VICEMINISTERIO DE DESARROLLO RURAL- MA,250000.0,7175.0,47641.83,6589.14,3846.30,65252.27,184747.73
7,FARUK GARIB ARBAJE,ASESOR,MINISTERIO DE AGRICULTURA,250000.0,7175.0,47641.83,6589.14,6325.00,67730.97,182269.03
8,RAFAEL ANTONIO ORTIZ QUEZADA,VICEMINISTRO (A),VICEMINISTERIO DE ASUNTOS CIENTIFICOS Y TECNOL...,250000.0,7175.0,47641.83,6589.14,14937.39,76343.36,173656.64
9,LEONARDO ANTONIO FAÑA BATISTA,DIRECTOR (A),MINISTERIO DE AGRICULTURA,200000.0,5740.0,35627.87,6080.00,10550.00,57997.87,142002.13
10,RAFAEL ERNESTO SOTO SOTO,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA CENTRAL- MA,180000.0,5166.0,30923.37,5472.00,25.00,41586.37,138413.63
11,PABLO REINALDO DE MOYA MORAN,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORCENTRAL- MA,180000.0,5166.0,30923.37,5472.00,25.00,41586.37,138413.63
12,EDUARDO ANTONIO MERCEDES SANCHEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,180000.0,5166.0,30494.50,5472.00,3065.46,44197.96,135802.04
13,LUIS ERNESTO PEREZ CUEVAS,ASESOR,MINISTERIO DE AGRICULTURA,175000.0,5022.5,29747.24,5320.00,25.00,40114.74,134885.26
14,JUAN BAUTISTA MATEO VALDEZ,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA SUROESTE- MA,180000.0,5166.0,30923.37,5472.00,4225.00,45786.37,134213.63
15,FRANK MARTIN VENTURA BETANCES,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORDESTE-MA,180000.0,5166.0,30065.64,5472.00,5255.92,45959.56,134040.44
16,PEDRO CARLOS VERAS TAVAREZ,DIRECTOR FINANCIERO,DEPARTAMENTO FINANCIERO,170000.0,4879.0,28571.12,5168.00,25.00,38643.12,131356.88
17,GUSTAVO GUILLERMO DE JESUS GOMEZ THORMANN,DIRECTOR (A),DIRECCION ADMINISTRATIVA,170000.0,4879.0,28571.12,5168.00,25.00,38643.12,131356.88
18,YOHAN MANUEL LOPEZ DILONE,ASESOR (A),MINISTERIO DE AGRICULTURA,175000.0,5022.5,29747.24,5320.00,3796.30,43886.04,131113.96
19,PEDRO TRINIDAD LEDESMA,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NORTE- MA,180000.0,5166.0,30923.37,5472.00,8125.00,49686.37,130313.63
20,PABLO ANTONIO RODRIGUEZ NUÑEZ,ASESOR,MINISTERIO DE AGRICULTURA,175000.0,5022.5,29747.24,5320.00,6325.00,46414.74,128585.26
21,GREGORIO M. DE LOS SANTOS,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA SUR- MA,180000.0,5166.0,30923.37,5472.00,10125.00,51686.37,128313.63
22,LUCHY GUZMAN GERMAN DE MAYOL,ENCARGADO (A),DEPARTAMENTO DE DESARROLLO INSTITUCIONAL Y CAL...,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
23,JUAN RAMON ROMNEY MORENO,ASISTENTE,MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
24,MARILEIDY DE LA CRUZ CONCEPCION,COORDINADOR GENERAL,MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
25,ERNESTO MANUEL DE MOYA SANCHEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
26,ALBA KARINA SUAREZ SANTOS,DIRECTOR (A),DEPARTAMENTO DE ANALISIS Y GESTION OPERATIVA- MA,150000.0,4305.0,23866.62,4560.00,25.00,32756.62,117243.38
27,CESAR SANDINO DE JESUS REINOSO,SECRETARIO EJECUTIVO,VICEMINISTERIO DE PLANIFICACION SECTORIAL AGRO...,150000.0,4305.0,23866.62,4560.00,75.00,32806.62,117193.38
28,LIDIA MARLENE JONES CASTRO,COORDINADOR GENERAL,MINISTERIO DE AGRICULTURA,150000.0,4305.0,23866.62,4560.00,75.00,32806.62,117193.38
29,YENIRSE ADAIRYS TEJEDA VILLAR,ASISTENTE,MINISTERIO DE AGRICULTURA,145000.0,4161.5,22690.49,4408.00,25.00,31284.99,113715.01
30,MARCELINO ANTONIO VARGAS VARGAS,ASISTENTE ESPECIAL DEL MINISTRO,MINISTERIO DE AGRICULTURA,145000.0,4161.5,22690.49,4408.00,25.00,31284.99,113715.01
31,MANUEL EMILIO GONZALEZ TEJERA,ASESOR,DEPARTAMENTO DE ECONOMIA AGROPECUARIA Y ESTADI...,150000.0,4305.0,23866.62,4560.00,4625.00,37356.62,112643.38
32,CRISTOBAL OSVALDO GUERRERO CEDEÑO,DIRECTOR (A),DIRECCION REGIONAL AGROPECUARIA ESTE- MA,150000.0,4305.0,23866.62,4560.00,5053.40,37785.02,112214.98
33,JOSE RAFAEL ESCARRAMAN HERNANDEZ,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE PRODUCCION BAJO AMBIENTE PROTE...,145000.0,4161.5,22261.63,4408.00,2490.46,33321.59,111678.41
34,CARLIXTO TAPIA VILORIA,DIRECTOR (A),LABORATORIO DE MICROPROPAGACION DE PLANTAS IN ...,145000.0,4161.5,22261.63,4408.00,4177.96,35009.09,109990.91
35,LUISA JANELY PEREZ VALENTIN,DIRECTOR (A) PLANIFICACION Y DESARROLLO,DIRECCION DE PLANIFICACION Y DESARROLLO,140000.0,4018.0,21085.50,4256.00,3065.46,32424.96,107575.04
36,DAURY CEDEÑO HOLGUIN,COORDINADOR (A),MINISTERIO DE AGRICULTURA,135000.0,3874.5,20338.24,4104.00,25.00,28341.74,106658.26
37,YTALIA ALTAGRACIA VASQUEZ DE DIAZ,DIRECTOR (A) RECURSOS HUMANOS,DIRECCION DE RECURSOS HUMANOS- MA,135000.0,3874.5,20338.24,4104.00,2125.00,30441.74,104558.26
38,DANILO ABREU NUÑEZ,COORDINADOR (A),MINISTERIO DE AGRICULTURA,130000.0,3731.0,19162.12,3952.00,25.00,26870.12,103129.88
39,ELADIA OLIVA BELTRE DIAZ,ENC. DPTO. TESORERIA,DEPARTAMENTO DE TESORERIA,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
40,ROSA ELENA TEJADA SANCHEZ,ENCARGADO(A) DEPARTAMENTO,DEPARTAMENTO DE COOPERACION INTERNACIONAL,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
41,JUAN ADALBERTO HINOJOSA GOMEZ,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE CACAO,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
42,EDGAR ARNALDO PEREZ TAVERAS,ENCARGADO(A) DEPARTAMENTO,DEPARTAMENTO DE TRANSPORTACION,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
43,PEDRO PABLO JIMENEZ SOSA,ASISTENTE,MINISTERIO DE AGRICULTURA,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
44,RAUL REYNOSO REYES,ASISTENTE,MINISTERIO DE AGRICULTURA,125000.0,3587.5,17985.99,3800.00,25.00,25398.49,99601.51
45,FIORDANNA DE LA MAZA BENCOSME,ENCARGADO DE DEPARTAMENTO,DEPARTAMENTO DE ACCESO A LA INFORMACION- MA,125000.0,3587.5,17985.99,3800.00,75.00,25448.49,99551.51
46,LOURDES MICHELLE ROMAN ABUD DE BELTRE,ASISTENTE,MINISTERIO DE AGRICULTURA,125000.0,3587.5,17985.99,3800.00,75.00,25448.49,99551.51
47,KARINA SORIANO VICTORIANO,ENCARGADO (A),DEPARTAMENTO DE ECONOMIA AGROPECUARIA Y ESTADI...,125000.0,3587.5,17985.99,3800.00,1275.00,26648.49,98351.51
48,JUAN JOSE AYBAR RODRIGUEZ,ENC.DPTO.DE CONTABILIDAD,DEPARTAMENTO CONTABILIDAD,125000.0,3587.5,17557.13,3800.00,1790.46,26735.09,98264.91
49,SILVERIO RAFAEL CHAVEZ VARGAS,DIRECTOR (A),DIRECCION REGIONAL AGROPECUARIA NORTE- MA,125000.0,3587.5,17985.99,3800.00,1375.00,26748.49,98251.51
50,NELY ROBER RODRIGUEZ GOMEZ,DIRECTOR REGIONAL,DIRECCION REGIONAL AGROPECUARIA NOROESTE- MA,150000.0,4305.0,23866.62,4560.00,19695.76,52427.38,97572.62

In [ ]:
DF_Nomina_Agricultura_NETA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7794 entries, 0 to 7793
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        7794 non-null   object
 1   Cargo_Funcion          7794 non-null   object
 2   Locacion_Departamento  7794 non-null   object
 3   Salario_Bruto          7794 non-null   float64
 4   Descuento_AFP          7794 non-null   float64
 5   Descuento_ISR          7794 non-null   float64
 6   Descuento_SFS          7794 non-null   float64
 7   Otros_Descuentos       7794 non-null   float64
 8   Total_Descuentos       7794 non-null   float64
 9   Salario_Neto           7794 non-null   float64
dtypes: float64(7), object(3)
memory usage: 609.0+ KB

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

In [ ]:
DF_Nomina_ObrasPublicas_Bruta = pd.read_csv("ObrasPublicas_Nomina.csv")

In [ ]:
DF_Nomina_ObrasPublicas_Bruta

,MINISTERIO DE OBRAS PUBLICAS - MOPC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,DEPARTAMENTO DE NOMINA - NOVIEMBRE DEL 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RELACION DE EMPLEADOS FIJOS MOPC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Empleado (Nombres y Apellidos),Cargo,Departamento,Tipo de Empleado,Ingreso Bruto,Descuento AFP,Descuento ISR,Descuento SFS,Otros descuentos,Ingreso Neto,Carrera Adm,Tipo de Empleado/Cargo,Genero,NaN,NaN,NaN,NaN
3,EDUARDO ESTRELLA,MINISTRO (A),DESPACHO,FIJO,"300,000.00","8,610.00","59,783.08","6,589.14",0.00,"224,992.78",NO,1. LIBRE NOMBRAMIENTO Y REM.,M,NaN,NaN,NaN,NaN
4,PABLO GONZALEZ SUBERVI,DIRECTOR ADM. FINANCIERO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"180,000.00","5,166.00","30,443.42","5,472.00","38,220.69","98,753.11",NO,NaN,M,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_ObrasPublicas_Bruta.head(51)

,MINISTERIO DE OBRAS PUBLICAS - MOPC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,DEPARTAMENTO DE NOMINA - NOVIEMBRE DEL 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RELACION DE EMPLEADOS FIJOS MOPC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Empleado (Nombres y Apellidos),Cargo,Departamento,Tipo de Empleado,Ingreso Bruto,Descuento AFP,Descuento ISR,Descuento SFS,Otros descuentos,Ingreso Neto,Carrera Adm,Tipo de Empleado/Cargo,Genero,NaN,NaN,NaN,NaN
3,EDUARDO ESTRELLA,MINISTRO (A),DESPACHO,FIJO,"300,000.00","8,610.00","59,783.08","6,589.14",0.00,"224,992.78",NO,1. LIBRE NOMBRAMIENTO Y REM.,M,NaN,NaN,NaN,NaN
4,PABLO GONZALEZ SUBERVI,DIRECTOR ADM. FINANCIERO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"180,000.00","5,166.00","30,443.42","5,472.00","38,220.69","98,753.11",NO,NaN,M,NaN,NaN,NaN,NaN
5,FIOR DÏ ALIZA MAGALIS CASTRO ESPINAL,COORDINADOR DESPACHO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"220,000.00","6,314.00","39,877.14","6,589.14","1,919.80","163,355.14",NO,NaN,F,NaN,NaN,NaN,NaN
6,JOSE EDUARDO PIMENTEL VALENZUELA,COORDINADOR GENERAL,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"240,000.00","6,888.00","45,213.58","6,589.14","5,759.40","175,524.88",NO,NaN,M,NaN,NaN,NaN,NaN
7,EDUARDO JOSE COMARAZAMY RIJO,COORDINADOR GENERAL,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"175,000.00","5,022.50","29,747.24","5,320.00",0.00,"134,885.26",NO,NaN,M,NaN,NaN,NaN,NaN
8,YUNE SALVADOR KHOURY FIGUEREO,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"150,000.00","4,305.00","23,866.62","4,560.00",0.00,"117,243.38",NO,NaN,M,NaN,NaN,NaN,NaN
9,MARIA ALTAGRACIA DEL C MARIANO TEJEDA,ASESOR (A),MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"220,000.00","6,314.00","40,357.08","6,589.14",0.00,"166,714.78",NO,1. LIBRE NOMBRAMIENTO Y REM.,F,NaN,NaN,NaN,NaN
10,RAUL BARTOLOME REYNOSO,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"100,000.00","2,870.00","12,105.37","3,040.00",0.00,"81,959.63",NO,NaN,M,NaN,NaN,NaN,NaN
11,CLAUDIA ROSA BASILIS CASTILLO,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"175,000.00","5,022.50","29,747.24","5,320.00","85,529.42","49,355.84",NO,NaN,F,NaN,NaN,NaN,NaN
12,NORBERTO JOSE ROJAS MERCEDES,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"175,000.00","5,022.50","29,747.24","5,320.00",0.00,"134,885.26",NO,NaN,M,NaN,NaN,NaN,NaN
13,FERNANDO ALFONSO SURIEL PORTELA,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"175,000.00","5,022.50","29,747.24","5,320.00","4,264.12","130,621.14",NO,NaN,M,NaN,NaN,NaN,NaN
14,RICARDO PEÑA ACEVEDO,ASESOR (A),MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"160,000.00","4,592.00","26,218.87","4,864.00","14,139.60","110,160.53",NO,NaN,M,NaN,NaN,NaN,NaN
15,JOAQUIN ANTONIO DIAZ ORTEGA,ASESOR (A),MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"175,000.00","5,022.50","29,747.24","5,320.00",0.00,"134,885.26",NO,NaN,M,NaN,NaN,NaN,NaN
16,JOSE EROSTIDES AYBAR OTERO,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"175,000.00","5,022.50","29,747.24","5,320.00",0.00,"134,885.26",NO,NaN,M,NaN,NaN,NaN,NaN
17,FELIX DAMIAN OLIVARES GRULLON,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"220,000.00","6,314.00","40,357.08","6,589.14",0.00,"166,714.78",NO,NaN,M,NaN,NaN,NaN,NaN
18,ROSA JUDITH DE PEÑA DE LA ROSA,ASESOR (A),MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"150,000.00","4,305.00","23,866.62","4,560.00",0.00,"117,243.38",NO,NaN,F,NaN,NaN,NaN,NaN
19,AQUILES ANTHONY REYNOSO HENRIQUEZ,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"100,000.00","2,870.00","12,105.37","3,040.00",0.00,"81,959.63",NO,NaN,M,NaN,NaN,NaN,NaN
20,ALBERTO CANAHUATE GONZALEZ,ASESOR,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"150,000.00","4,305.00","23,866.62","4,560.00","9,236.06","108,007.32",NO,NaN,M,NaN,NaN,NaN,NaN
21,YAMILKA VERAS RODRIGUEZ,ASISTENTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"80,000.00","2,296.00","7,400.87","2,432.00",0.00,"67,846.13",NO,NaN,F,NaN,NaN,NaN,NaN
22,MICHAEL ANTONIO POLANCO WILMOT,MEDICO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"50,000.00","1,435.00","1,854.00","1,520.00",0.00,"45,166.00",NO,NaN,M,NaN,NaN,NaN,NaN
23,MARIA ISABEL REYES DE PEÑA,ASISTENTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"110,000.00","3,157.00","14,457.62","3,344.00",0.00,"89,016.38",NO,NaN,F,NaN,NaN,NaN,NaN
24,WENDY MAÑON GONZALEZ,ASISTENTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"85,000.00","2,439.50","8,576.99","2,584.00",0.00,"71,374.51",NO,NaN,F,NaN,NaN,NaN,NaN
25,YSAURIS RAQUEL GOMEZ DE LEON,ASISTENTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"75,000.00","2,152.50","6,309.38","2,280.00",0.00,"64,233.12",NO,NaN,F,NaN,NaN,NaN,NaN
26,MATILDE DIAZ ABREU,ASISTENTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"110,000.00","3,157.00","14,457.62","3,344.00",0.00,"89,016.38",NO,NaN,F,NaN,NaN,NaN,NaN
27,PASCUAL ANTONIO GOMEZ GUILLEN,AUXILIAR OFICINA,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"20,000.00",574.00,0.00,608.00,0.00,"18,793.00",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
28,MONICA GONZALEZ DIAZ,RECEPCIONISTA,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"20,000.00",574.00,0.00,608.00,0.00,"16,873.22",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
29,NICOLE DECAMPS TREMOLS,AUXILIAR ADMINISTRATIVO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"40,000.00","1,148.00",442.65,"1,216.00",0.00,"37,168.35",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
30,GUILLERMO MORONTA,SUPERVISOR MANTENIMIENTO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"25,000.00",717.50,0.00,760.00,0.00,"23,497.50",NO,NaN,M,NaN,NaN,NaN,NaN
31,ROSARIO DEL SOCORRO LANTIGUA,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"22,000.00",631.40,0.00,668.80,"1,000.00","13,915.46",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
32,IVELISSE JIMENEZ DE LOS SANTOS,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"22,000.00",631.40,0.00,668.80,500.00,"20,174.80",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
33,ANGEL GABRIEL GUANCE,CHOFER,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"25,000.00",717.50,0.00,760.00,"7,300.73","16,196.77",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
34,LEONIDAS MARGARITA JIMENEZ ALCANTARA,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"22,000.00",631.40,0.00,668.80,"8,887.30","11,787.50",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
35,PEDRO JAVIER MOSCAT MARTINEZ,SEGURIDAD,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"23,000.00",660.10,0.00,699.20,0.00,"21,615.70",NO,NaN,M,NaN,NaN,NaN,NaN
36,MARGARET KISMAIRI ROCHE DIAZ,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"18,000.00",516.60,0.00,547.20,0.00,"16,911.20",NO,NaN,F,NaN,NaN,NaN,NaN
37,ANDREA CEPIN MANZUETA,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"22,000.00",631.40,0.00,668.80,0.00,"20,674.80",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
38,OLGA LIDIA JIMENEZ MILIANO,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"20,000.00",574.00,0.00,608.00,0.00,"18,793.00",NO,NaN,F,NaN,NaN,NaN,NaN
39,JACQUELINE BATISTA PEREZ,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"16,500.00",473.55,0.00,501.60,0.00,"15,499.85",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
40,AGUEDO FABIAN GUILLOT,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"11,000.00",315.70,0.00,334.40,0.00,"10,324.90",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
41,SATURNINA NUÑEZ LINARES,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"22,000.00",631.40,0.00,668.80,"1,000.00","19,674.80",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
42,MIRTHA ALCANTARA DE LOS SANTOS,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"15,000.00",430.50,0.00,456.00,"5,500.00","8,588.50",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
43,BERTA SCARLET MABEL CAMINERO PAREDES,MENSAJERO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"19,800.00",568.26,0.00,601.92,"3,621.26","14,983.56",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
44,FRANCISCA MERCEDES MONTAS,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"17,000.00",487.90,0.00,516.80,0.00,"15,970.30",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
45,JORGE ESPINAL INFANTE,CHOFER,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"30,000.00",861.00,0.00,912.00,"1,000.00","27,202.00",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
46,RAMON MEJIA ZACARIAS,VIGILANTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"12,000.00",344.40,0.00,364.80,0.00,"11,265.80",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
47,JUAN NUÑEZ SIRI,VIGILANTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"11,000.00",315.70,0.00,334.40,"1,177.00","9,147.90",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
48,EDUVIRGEN DELGADO SANCHEZ,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"20,000.00",574.00,0.00,608.00,0.00,"18,793.00",NO,3. ESTATUTO SIMPLIFICADO,F,NaN,NaN,NaN,NaN
49,ELIAS DAVID CUEVAS PEREZ,VIGILANTE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"25,000.00",717.50,0.00,760.00,0.00,"23,497.50",NO,3. ESTATUTO SIMPLIFICADO,M,NaN,NaN,NaN,NaN
50,YUBERKIS IVELISSE MARTINEZ PINEDA,CONSERJE,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,FIJO,"18,000.00",516.60,0.00,547.20,0.00,"16,911.20",NO,NaN,F,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_ObrasPublicas_Bruta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5383 entries, 0 to 5382
Data columns (total 17 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   MINISTERIO DE OBRAS PUBLICAS - MOPC   4832 non-null   object
 1   Unnamed: 1                            4830 non-null   object
 2   Unnamed: 2                            4830 non-null   object
 3   Unnamed: 3                            4830 non-null   object
 4   Unnamed: 4                            4830 non-null   object
 5   Unnamed: 5                            4830 non-null   object
 6   Unnamed: 6                            4830 non-null   object
 7   Unnamed: 7                            4830 non-null   object
 8   Unnamed: 8                            4830 non-null   object
 9   Unnamed: 9                            4830 non-null   object
 10  Unnamed: 10                           4830 non-null   object
 11  Unnamed: 11                           2457 non-null   object
 12  Unnamed: 12                           4830 non-null   object
 13  Unnamed: 13                           0 non-null      float64
 14  Unnamed: 14                           0 non-null      float64
 15  Unnamed: 15                           0 non-null      float64
 16  Unnamed: 16                           0 non-null      float64
dtypes: float64(4), object(13)
memory usage: 715.1+ KB

In [ ]:
# 1. Crear copia de la tabla original
DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_Bruta.copy()

# 2. Renombrar columnas (por posición, no por nombre específico)
column_renames = {
    DF_Nomina_ObrasPublicas_NETA.columns[0]: 'Nombre_Completo',
    DF_Nomina_ObrasPublicas_NETA.columns[1]: 'Cargo_Funcion',
    DF_Nomina_ObrasPublicas_NETA.columns[2]: 'Locacion_Departamento',
    DF_Nomina_ObrasPublicas_NETA.columns[4]: 'Salario_Bruto',
    DF_Nomina_ObrasPublicas_NETA.columns[5]: 'Descuento_AFP',
    DF_Nomina_ObrasPublicas_NETA.columns[6]: 'Descuento_ISR',
    DF_Nomina_ObrasPublicas_NETA.columns[7]: 'Descuento_SFS',
    DF_Nomina_ObrasPublicas_NETA.columns[8]: 'Otros_Descuentos',
    DF_Nomina_ObrasPublicas_NETA.columns[9]: 'Salario_Neto'
}

DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA.rename(columns=column_renames)

# 3. Función para limpiar números
def limpiar_numero(valor):
    if isinstance(valor, str):
        valor_limpio = valor.replace('$', '').replace(',', '').strip()
        try:
            return float(valor_limpio)
        except:
            return 0.0
    elif pd.isna(valor):
        return 0.0
    else:
        return float(valor)

# 4. Limpiar columnas numéricas
columnas_numericas = ['Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
                      'Descuento_SFS', 'Otros_Descuentos', 'Salario_Neto']

for col in columnas_numericas:
    DF_Nomina_ObrasPublicas_NETA[col] = DF_Nomina_ObrasPublicas_NETA[col].apply(limpiar_numero)

# 5. Calcular Total_Descuentos
DF_Nomina_ObrasPublicas_NETA['Total_Descuentos'] = (
    DF_Nomina_ObrasPublicas_NETA['Descuento_AFP'] +
    DF_Nomina_ObrasPublicas_NETA['Descuento_ISR'] +
    DF_Nomina_ObrasPublicas_NETA['Descuento_SFS'] +
    DF_Nomina_ObrasPublicas_NETA['Otros_Descuentos']
)

# 6. Seleccionar columnas finales
columnas_finales = [
    'Nombre_Completo',
    'Cargo_Funcion',
    'Locacion_Departamento',
    'Salario_Bruto',
    'Descuento_AFP',
    'Descuento_ISR',
    'Descuento_SFS',
    'Otros_Descuentos',
    'Total_Descuentos',
    'Salario_Neto'
]

DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA[columnas_finales]

# 7. Asegurar tipos de datos
DF_Nomina_ObrasPublicas_NETA['Nombre_Completo'] = DF_Nomina_ObrasPublicas_NETA['Nombre_Completo'].astype(str)
DF_Nomina_ObrasPublicas_NETA['Cargo_Funcion'] = DF_Nomina_ObrasPublicas_NETA['Cargo_Funcion'].astype(str)
DF_Nomina_ObrasPublicas_NETA['Locacion_Departamento'] = DF_Nomina_ObrasPublicas_NETA['Locacion_Departamento'].astype(str)

for col in ['Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS',
            'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']:
    DF_Nomina_ObrasPublicas_NETA[col] = DF_Nomina_ObrasPublicas_NETA[col].astype('float64')

In [ ]:
DF_Nomina_ObrasPublicas_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,DEPARTAMENTO DE NOMINA - NOVIEMBRE DEL 2025,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,RELACION DE EMPLEADOS FIJOS MOPC,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00
2,Empleado (Nombres y Apellidos),Cargo,Departamento,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,EDUARDO ESTRELLA,MINISTRO (A),DESPACHO,300000.0,8610.0,59783.08,6589.14,0.00,74982.22,224992.78
4,PABLO GONZALEZ SUBERVI,DIRECTOR ADM. FINANCIERO,MINISTERIO DE OBRAS PUBLICAS Y COMUNICACIONES,180000.0,5166.0,30443.42,5472.00,38220.69,79302.11,98753.11
...,...,...,...,...,...,...,...,...,...,...
5378,nan,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00
5379,nan,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00
5380,nan,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00
5381,nan,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00
5382,nan,nan,nan,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [ ]:
# VERSIÓN CON VERIFICACIÓN

filas_iniciales = len(DF_Nomina_ObrasPublicas_NETA)

# 1. Eliminar filas no deseadas
mascara = (
    DF_Nomina_ObrasPublicas_NETA['Nombre_Completo'].astype(str).str.contains('DEPARTAMENTO DE NOMINA', case=False, na=False) |
    DF_Nomina_ObrasPublicas_NETA['Nombre_Completo'].astype(str).str.contains('RELACION DE EMPLEADOS', case=False, na=False) |
    DF_Nomina_ObrasPublicas_NETA['Nombre_Completo'].astype(str).str.contains('Empleado (Nombres y Apellidos)', case=False, na=False)
)
DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA[~mascara]
eliminados_paso1 = filas_iniciales - len(DF_Nomina_ObrasPublicas_NETA)

# 2. Eliminar nulos
antes_nulos = len(DF_Nomina_ObrasPublicas_NETA)
DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA.dropna()
eliminados_paso2 = antes_nulos - len(DF_Nomina_ObrasPublicas_NETA)

# 3. Eliminar duplicados
antes_dups = len(DF_Nomina_ObrasPublicas_NETA)
DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA.sort_values('Salario_Neto', ascending=False)
DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA.drop_duplicates(subset=['Nombre_Completo'], keep='first')
DF_Nomina_ObrasPublicas_NETA = DF_Nomina_ObrasPublicas_NETA.reset_index(drop=True)
eliminados_paso3 = antes_dups - len(DF_Nomina_ObrasPublicas_NETA)

print(f"Resumen de limpieza:")
print(f"- Filas iniciales: {filas_iniciales}")
print(f"- Eliminadas (encabezados): {eliminados_paso1}")
print(f"- Eliminadas (nulos): {eliminados_paso2}")
print(f"- Eliminadas (duplicados): {eliminados_paso3}")
print(f"- Filas finales: {len(DF_Nomina_ObrasPublicas_NETA)}")

Resumen de limpieza:
- Filas iniciales: 5383
- Eliminadas (encabezados): 2
- Eliminadas (nulos): 0
- Eliminadas (duplicados): 550
- Filas finales: 4831

/tmp/ipython-input-578472674.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  DF_Nomina_ObrasPublicas_NETA['Nombre_Completo'].astype(str).str.contains('Empleado (Nombres y Apellidos)', case=False, na=False)

In [ ]:
DF_Nomina_ObrasPublicas_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EDUARDO ESTRELLA,MINISTRO (A),DESPACHO,300000.00,8610.00,59783.08,6589.14,0.00,74982.22,224992.78
1,FERNANDO AUGUSTO MOORE GUZMAN,VICEMINISTRO (A),VICEMINISTERIO DE PLANIFICACION Y REGULACION T...,240000.00,6888.00,45213.58,6589.14,0.00,58690.72,181284.28
2,TOMASINA PASCUAL FANIT,VICEMINISTRO (A),DIRECCION DE GERENCIA DE PROYECTOS,240000.00,6888.00,45213.58,6589.14,0.00,58690.72,181284.28
3,OLIVER JOSE NAZARIO BRUGAL,VICEMINISTRO (A),VICEMINISTERIO DE COORDINACION REGIONAL,240000.00,6888.00,45213.58,6589.14,0.00,58690.72,181284.28
4,FERNANDO HIRAM TAVERAS RODRIGUEZ,VICEMINISTRO (A),VICEMINISTERIO DE MANTENIMIENTO VIAL,240000.00,6888.00,45213.58,6589.14,0.00,58690.72,181284.28
...,...,...,...,...,...,...,...,...,...,...
4826,LUCRECIA ANTONIA SANTANA SEVERINO,AUXILIAR,DEPARTAMENTO PROVINCIALES,10000.00,287.00,0.00,304.00,5344.44,5935.44,200.00
4827,EDWIN SANTIAGO SALAZAR VASQUEZ,AUXILIAR OFICINA,SECCION DE IMPRENTA,12485.15,358.32,0.00,379.55,7682.72,8420.59,200.00
4828,JOSE RAMON PEREZ CESPEDES,ALBAÑIL,DIVISION DE PERSONAL DE BRIGADAS,18000.00,516.60,0.00,547.20,12871.64,13935.44,200.00
4829,nan,nan,nan,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4830,Empleado (Nombres y Apellidos),Cargo,Departamento,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [ ]:
DF_Nomina_ObrasPublicas_NETA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4831 entries, 0 to 4830
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        4831 non-null   object
 1   Cargo_Funcion          4831 non-null   object
 2   Locacion_Departamento  4831 non-null   object
 3   Salario_Bruto          4831 non-null   float64
 4   Descuento_AFP          4831 non-null   float64
 5   Descuento_ISR          4831 non-null   float64
 6   Descuento_SFS          4831 non-null   float64
 7   Otros_Descuentos       4831 non-null   float64
 8   Total_Descuentos       4831 non-null   float64
 9   Salario_Neto           4831 non-null   float64
dtypes: float64(7), object(3)
memory usage: 377.6+ KB

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

In [ ]:
DF_Nomina_Aduanas_Bruta = pd.read_csv("Aduanas_Nomina.csv")

In [ ]:
DF_Nomina_Aduanas_Bruta

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,DIRECCIÓN GENERAL DE ADUANAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GERENCIA FINANCIERA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NÓMINA DE EMPLEADOS Y FUNCIONARIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PERSONAL FIJO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OCTUBRE 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_Aduanas_Bruta.head(51)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,DIRECCIÓN GENERAL DE ADUANAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GERENCIA FINANCIERA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NÓMINA DE EMPLEADOS Y FUNCIONARIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PERSONAL FIJO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OCTUBRE 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CANT.,NOMBRE (S) Y APELLIDO (S),POSICIÓN,AREA,GENERO,TIPO EMPLEADO,SALARIO,AFP,SFS,ISR,OTROS DESC.,INGRESO NETO
8,1,EDUARDO JOSE SANZ LOVATON,DIRECTOR GENERAL,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"630,919.00","12,441.34","6,589.14","140,697.34","3,455.92","467,735.26"
9,2,EDUARDO RAMON RODRIGUEZ APOLINARIO,ASESOR,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"323,856.00","9,294.67","6,589.14","65,575.99","65,933.17","176,463.03"
10,3,ANIBELCA MARIA MENA SUSANA,COORDINADOR DEL DESPACHO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"323,856.00","9,294.67","6,589.14","65,575.99","47,381.80","195,014.40"
11,4,JUAN BAUTISTA VICENS BELLO,ASESOR,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"323,856.00","9,294.67","6,589.14","65,575.99",25.00,"242,371.20"
12,5,OSCAR ORLANDO D'OLEO SEIFFE,GERENTE LEGAL,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"301,987.00","8,667.03","6,589.14","60,265.65",25.00,"226,440.18"
13,6,EDUARDO LUIS PRESINAL,COORDINADOR DE RELACIONES GUBERNAME,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"300,000.00","8,610.00","6,589.14","59,783.15","14,131.43","210,886.28"
14,7,LEIVIN ESENOBEL GUERRERO,ASESOR,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"300,000.00","8,610.00","6,589.14","59,783.15",25.00,"224,992.71"
15,8,RHADAMES CARLOS MANUEL MATEO VARGAS,GERENTE DE AUDITORIA INTERNA,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"250,000.00","7,175.00","6,589.14","46,784.17","11,480.27","177,971.42"
16,9,EDUARDO PASCUAL PALACIOS NUÑEZ,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"232,444.00","6,671.14","6,589.14","43,378.87","19,225.00","156,579.85"
17,10,NORAH RAQUEL GERMAN GALVEZ,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"200,000.00","5,740.00","6,080.00","35,627.94",25.00,"152,527.06"
18,11,REYNALDO ADRIAN GUILAMO PILIER,COORDINADOR GENERAL,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"200,000.00","5,740.00","6,080.00","35,627.94","7,083.00","145,469.06"
19,12,JOSE FERNANDO HENRIQUEZ ROBIOU,COORDINADOR DE AUDITORIA,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"180,000.00","5,166.00","5,472.00","30,923.44",180.06,"138,258.50"
20,13,SIMON DARIO RODRIGUEZ PEREYRA,ASESOR DE ESTRATEGIA COMUNICACIONAL,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"170,000.00","4,879.00","5,168.00","28,571.19",25.00,"131,356.81"
21,14,OLGA DAISY FERNANDEZ ENCARNACION,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"157,500.00","4,520.25","4,788.00","25,630.87","4,525.00","118,035.88"
22,15,MIGUEL ANGEL CAMPOS GUERRERO,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"150,000.00","4,305.00","4,560.00","23,866.69","3,540.70","113,727.61"
23,16,CARLOS GABRIEL FERNANDEZ TAVERAS,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"150,000.00","4,305.00","4,560.00","23,008.96","12,748.57","105,377.47"
24,17,FRANCISCO ROSENDO MOYA TAVAREZ,COORDINADOR DE AUDITORIA,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"150,000.00","4,305.00","4,560.00","23,866.69","1,903.00","115,365.31"
25,18,OLIVER ALEXANDER D'OLEO SEIFFE,ENCARGADO SECCION ADMINISTRATIVA,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"125,000.00","3,587.50","3,800.00","17,986.06","2,421.00","97,205.44"
26,19,LARISSA MARGARITA COLON ISA,COORDINADOR,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"120,000.00","3,444.00","3,648.00","16,809.94","9,884.65","86,213.41"
27,20,ANTONIO DE JESUS OLIVO LEON,SUB-ENCARGADO DEPARTAMENTO JURIDICO,DESPACHO DEL DIRECTOR,MASCULINO,CARRERA,"110,000.00","3,157.00","3,344.00","13,599.96","7,433.92","82,465.12"
28,21,BASILIO DOTEL MENDEZ,ABOGADO I,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"100,000.00","2,870.00","3,040.00","12,105.44",25.00,"81,959.56"
29,22,GABRIELA MASSIEL TEJERA GRULLON,COORDINADOR JURIDICO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"100,000.00","2,870.00","3,040.00","12,105.44",25.00,"81,959.56"
30,23,JUAN CARLOS BULLI,ABOGADO I,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"100,000.00","2,870.00","3,040.00","12,105.44","1,743.25","80,241.31"
31,24,MARY LUZ DE LA HOZ DE LA HOZ,COORDINADOR TECNICO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"99,750.00","2,862.83","3,032.40","11,617.77","26,792.68","55,444.32"
32,25,NIURKA MELANIA BEATO ALBA,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,FEMENINO,CARRERA,"96,638.00","2,773.51","2,937.80","11,314.61","21,318.06","58,294.02"
33,26,MARIA VIRGINIA GARCIA PERDOMO,COORDINADOR DE COMUNICACIONES,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"96,638.00","2,773.51","2,937.80","11,314.61",25.00,"79,587.08"
34,27,ROSA ADELA BAEZ DIAZ,SECRETARIA EJECUTIVA I,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"90,000.00","2,583.00","2,736.00","9,753.19","4,544.00","70,383.81"
35,28,GEORGE DEVANJELO SANTANA DEL VILLAR,ABOGADO,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"90,000.00","2,583.00","2,736.00","9,753.19","9,335.12","65,592.69"
36,29,JOSE CHIA SANCHEZ,COORDINADOR LEGAL,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"90,000.00","2,583.00","2,736.00","9,753.19",844.00,"74,083.81"
37,30,JANNA SHAYRILIN SAPEG MENDEZ,ABOGADO I,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"85,000.00","2,439.50","2,584.00","8,577.06","1,207.44","70,192.00"
38,31,ISIDRO PEÑA,AUDITOR,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"85,000.00","2,439.50","2,584.00","8,577.06","43,642.45","27,756.99"
39,32,CRYSTAL JOSELYN SANTANA ABREU,ABOGADO I,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"85,000.00","2,439.50","2,584.00","8,577.06","1,197.87","70,201.57"
40,33,KIARA YOSSIRIS TAVERAS TAPIA,ENCARGADO AUDITORIA DE GESTION,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"84,923.00","2,437.29","2,581.66","8,130.08","5,698.41","66,075.56"
41,34,MAYRA L DE LOS MILAGROS MUÑOZ CONTRERAS,ENCARGADO DE AUDITORIA DE TI,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"80,000.00","2,296.00","2,432.00","7,400.94","1,304.00","66,567.06"
42,35,CARLOS EDUARDO CONTIN TEJEDA,ABOGADO,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"80,000.00","2,296.00","2,432.00","7,400.94","9,742.55","58,128.51"
43,36,ANA ISABEL RAMIREZ ROSA,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"80,000.00","2,296.00","2,432.00","7,400.94","10,929.32","56,941.74"
44,37,GLENIS GRABIELA REYNOSO TAVERAS,COORDINADOR TECNICO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"77,000.00","2,209.90","2,340.80","6,695.26","4,405.85","61,348.19"
45,38,JULISSA MARIA SANCHEZ DICKSON,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"77,000.00","2,209.90","2,340.80","6,342.62","11,816.91","54,289.77"
46,39,WILDA MARIA CABRAL CARMONA,COORDINADOR TECNICO,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"75,000.00","2,152.50","2,280.00","6,309.35","11,489.25","52,768.90"
47,40,PAMELA ELISA PIÑEYRO PELLERANO,ASISTENTE LEGAL,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"75,000.00","2,152.50","2,280.00","5,623.17","32,166.57","32,777.76"
48,41,GREGORY MANUEL CONCEPCION POURIET HOLGUIN,AUDITOR,DESPACHO DEL DIRECTOR,MASCULINO,FIJO,"75,000.00","2,152.50","2,280.00","6,309.35","6,636.21","57,621.94"
49,42,FRANCIS YOLANDA ALBERTINA TAVERAS PICHARDO,ENCARGADO AUDITORIA OPERATIVA,DESPACHO DEL DIRECTOR,FEMENINO,FIJO,"72,389.00","2,077.56","2,200.63","5,474.92","2,018.46","60,617.43"
50,43,ROSANNA MARIA TORRES DIAZ,ENCARGADO DE AUDITORIA ZONA NORTE,DESPACHO DEL DIRECTOR,FEMENINO,CARRERA,"72,000.00","2,066.40","2,188.80","5,744.81","14,764.82","47,235.17"

In [ ]:
DF_Nomina_Aduanas_Bruta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3469 entries, 0 to 3468
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   3455 non-null   object
 1   Unnamed: 1   3450 non-null   object
 2   Unnamed: 2   3450 non-null   object
 3   Unnamed: 3   3450 non-null   object
 4   Unnamed: 4   3450 non-null   object
 5   Unnamed: 5   3450 non-null   object
 6   Unnamed: 6   3450 non-null   object
 7   Unnamed: 7   3450 non-null   object
 8   Unnamed: 8   3450 non-null   object
 9   Unnamed: 9   3450 non-null   object
 10  Unnamed: 10  3450 non-null   object
 11  Unnamed: 11  3450 non-null   object
dtypes: object(12)
memory usage: 325.3+ KB

In [ ]:
# 1. Crear una copia del DataFrame original para no modificarlo
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_Bruta.copy()

# 2. Eliminar las primeras filas que contienen información de encabezado
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA.iloc[8:].reset_index(drop=True)

# 3. Renombrar las columnas según el esquema original
DF_Nomina_Aduanas_NETA.columns = [
    'Cantidad', 'Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento',
    'Genero', 'Tipo_Empleado', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_SFS',
    'Descuento_ISR', 'Otros_Descuentos', 'Salario_Neto'
]

# 4. Seleccionar solo las columnas que necesitas
columnas_necesarias = [
    'Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento',
    'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS',
    'Otros_Descuentos', 'Salario_Neto'
]

DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA[columnas_necesarias]

# 5. Calcular la columna Total_Descuentos sumando todos los descuentos
DF_Nomina_Aduanas_NETA['Total_Descuentos'] = (
    DF_Nomina_Aduanas_NETA['Descuento_AFP'].astype(str).str.replace(',', '').astype(float) +
    DF_Nomina_Aduanas_NETA['Descuento_ISR'].astype(str).str.replace(',', '').astype(float) +
    DF_Nomina_Aduanas_NETA['Descuento_SFS'].astype(str).str.replace(',', '').astype(float) +
    DF_Nomina_Aduanas_NETA['Otros_Descuentos'].astype(str).str.replace(',', '').astype(float)
)

# 6. Convertir las columnas numéricas a float (eliminando comas de miles)
columnas_numericas = [
    'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
    'Descuento_SFS', 'Otros_Descuentos', 'Salario_Neto'
]

for col in columnas_numericas:
    DF_Nomina_Aduanas_NETA[col] = DF_Nomina_Aduanas_NETA[col].astype(str).str.replace(',', '').astype(float)

# 7. Reordenar las columnas en el orden solicitado
columnas_ordenadas = [
    'Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento',
    'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS',
    'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto'
]

DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA[columnas_ordenadas]

# 8. Convertir las columnas de texto a string (object) y limpiar espacios
columnas_texto = ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento']
for col in columnas_texto:
    DF_Nomina_Aduanas_NETA[col] = DF_Nomina_Aduanas_NETA[col].astype(str).str.strip()

In [ ]:
DF_Nomina_Aduanas_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EDUARDO JOSE SANZ LOVATON,DIRECTOR GENERAL,DESPACHO DEL DIRECTOR,630919.0,12441.34,140697.34,6589.14,3455.92,163183.74,467735.26
1,EDUARDO RAMON RODRIGUEZ APOLINARIO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,65933.17,147392.97,176463.03
2,ANIBELCA MARIA MENA SUSANA,COORDINADOR DEL DESPACHO,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,47381.80,128841.60,195014.40
3,JUAN BAUTISTA VICENS BELLO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
4,OSCAR ORLANDO D'OLEO SEIFFE,GERENTE LEGAL,DESPACHO DEL DIRECTOR,301987.0,8667.03,60265.65,6589.14,25.00,75546.82,226440.18
...,...,...,...,...,...,...,...,...,...,...
3456,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3457,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3458,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3459,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3460,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_Aduanas_NETA.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EDUARDO JOSE SANZ LOVATON,DIRECTOR GENERAL,DESPACHO DEL DIRECTOR,630919.0,12441.34,140697.34,6589.14,3455.92,163183.74,467735.26
1,EDUARDO RAMON RODRIGUEZ APOLINARIO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,65933.17,147392.97,176463.03
2,ANIBELCA MARIA MENA SUSANA,COORDINADOR DEL DESPACHO,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,47381.80,128841.60,195014.40
3,JUAN BAUTISTA VICENS BELLO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
4,OSCAR ORLANDO D'OLEO SEIFFE,GERENTE LEGAL,DESPACHO DEL DIRECTOR,301987.0,8667.03,60265.65,6589.14,25.00,75546.82,226440.18
5,EDUARDO LUIS PRESINAL,COORDINADOR DE RELACIONES GUBERNAME,DESPACHO DEL DIRECTOR,300000.0,8610.00,59783.15,6589.14,14131.43,89113.72,210886.28
6,LEIVIN ESENOBEL GUERRERO,ASESOR,DESPACHO DEL DIRECTOR,300000.0,8610.00,59783.15,6589.14,25.00,75007.29,224992.71
7,RHADAMES CARLOS MANUEL MATEO VARGAS,GERENTE DE AUDITORIA INTERNA,DESPACHO DEL DIRECTOR,250000.0,7175.00,46784.17,6589.14,11480.27,72028.58,177971.42
8,EDUARDO PASCUAL PALACIOS NUÑEZ,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,232444.0,6671.14,43378.87,6589.14,19225.00,75864.15,156579.85
9,NORAH RAQUEL GERMAN GALVEZ,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,200000.0,5740.00,35627.94,6080.00,25.00,47472.94,152527.06
10,REYNALDO ADRIAN GUILAMO PILIER,COORDINADOR GENERAL,DESPACHO DEL DIRECTOR,200000.0,5740.00,35627.94,6080.00,7083.00,54530.94,145469.06
11,JOSE FERNANDO HENRIQUEZ ROBIOU,COORDINADOR DE AUDITORIA,DESPACHO DEL DIRECTOR,180000.0,5166.00,30923.44,5472.00,180.06,41741.50,138258.50
12,SIMON DARIO RODRIGUEZ PEREYRA,ASESOR DE ESTRATEGIA COMUNICACIONAL,DESPACHO DEL DIRECTOR,170000.0,4879.00,28571.19,5168.00,25.00,38643.19,131356.81
13,OLGA DAISY FERNANDEZ ENCARNACION,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,157500.0,4520.25,25630.87,4788.00,4525.00,39464.12,118035.88
14,MIGUEL ANGEL CAMPOS GUERRERO,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,150000.0,4305.00,23866.69,4560.00,3540.70,36272.39,113727.61
15,CARLOS GABRIEL FERNANDEZ TAVERAS,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,150000.0,4305.00,23008.96,4560.00,12748.57,44622.53,105377.47
16,FRANCISCO ROSENDO MOYA TAVAREZ,COORDINADOR DE AUDITORIA,DESPACHO DEL DIRECTOR,150000.0,4305.00,23866.69,4560.00,1903.00,34634.69,115365.31
17,OLIVER ALEXANDER D'OLEO SEIFFE,ENCARGADO SECCION ADMINISTRATIVA,DESPACHO DEL DIRECTOR,125000.0,3587.50,17986.06,3800.00,2421.00,27794.56,97205.44
18,LARISSA MARGARITA COLON ISA,COORDINADOR,DESPACHO DEL DIRECTOR,120000.0,3444.00,16809.94,3648.00,9884.65,33786.59,86213.41
19,ANTONIO DE JESUS OLIVO LEON,SUB-ENCARGADO DEPARTAMENTO JURIDICO,DESPACHO DEL DIRECTOR,110000.0,3157.00,13599.96,3344.00,7433.92,27534.88,82465.12
20,BASILIO DOTEL MENDEZ,ABOGADO I,DESPACHO DEL DIRECTOR,100000.0,2870.00,12105.44,3040.00,25.00,18040.44,81959.56
21,GABRIELA MASSIEL TEJERA GRULLON,COORDINADOR JURIDICO,DESPACHO DEL DIRECTOR,100000.0,2870.00,12105.44,3040.00,25.00,18040.44,81959.56
22,JUAN CARLOS BULLI,ABOGADO I,DESPACHO DEL DIRECTOR,100000.0,2870.00,12105.44,3040.00,1743.25,19758.69,80241.31
23,MARY LUZ DE LA HOZ DE LA HOZ,COORDINADOR TECNICO,DESPACHO DEL DIRECTOR,99750.0,2862.83,11617.77,3032.40,26792.68,44305.68,55444.32
24,NIURKA MELANIA BEATO ALBA,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,96638.0,2773.51,11314.61,2937.80,21318.06,38343.98,58294.02
25,MARIA VIRGINIA GARCIA PERDOMO,COORDINADOR DE COMUNICACIONES,DESPACHO DEL DIRECTOR,96638.0,2773.51,11314.61,2937.80,25.00,17050.92,79587.08
26,ROSA ADELA BAEZ DIAZ,SECRETARIA EJECUTIVA I,DESPACHO DEL DIRECTOR,90000.0,2583.00,9753.19,2736.00,4544.00,19616.19,70383.81
27,GEORGE DEVANJELO SANTANA DEL VILLAR,ABOGADO,DESPACHO DEL DIRECTOR,90000.0,2583.00,9753.19,2736.00,9335.12,24407.31,65592.69
28,JOSE CHIA SANCHEZ,COORDINADOR LEGAL,DESPACHO DEL DIRECTOR,90000.0,2583.00,9753.19,2736.00,844.00,15916.19,74083.81
29,JANNA SHAYRILIN SAPEG MENDEZ,ABOGADO I,DESPACHO DEL DIRECTOR,85000.0,2439.50,8577.06,2584.00,1207.44,14808.00,70192.00
30,ISIDRO PEÑA,AUDITOR,DESPACHO DEL DIRECTOR,85000.0,2439.50,8577.06,2584.00,43642.45,57243.01,27756.99
31,CRYSTAL JOSELYN SANTANA ABREU,ABOGADO I,DESPACHO DEL DIRECTOR,85000.0,2439.50,8577.06,2584.00,1197.87,14798.43,70201.57
32,KIARA YOSSIRIS TAVERAS TAPIA,ENCARGADO AUDITORIA DE GESTION,DESPACHO DEL DIRECTOR,84923.0,2437.29,8130.08,2581.66,5698.41,18847.44,66075.56
33,MAYRA L DE LOS MILAGROS MUÑOZ CONTRERAS,ENCARGADO DE AUDITORIA DE TI,DESPACHO DEL DIRECTOR,80000.0,2296.00,7400.94,2432.00,1304.00,13432.94,66567.06
34,CARLOS EDUARDO CONTIN TEJEDA,ABOGADO,DESPACHO DEL DIRECTOR,80000.0,2296.00,7400.94,2432.00,9742.55,21871.49,58128.51
35,ANA ISABEL RAMIREZ ROSA,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,80000.0,2296.00,7400.94,2432.00,10929.32,23058.26,56941.74
36,GLENIS GRABIELA REYNOSO TAVERAS,COORDINADOR TECNICO,DESPACHO DEL DIRECTOR,77000.0,2209.90,6695.26,2340.80,4405.85,15651.81,61348.19
37,JULISSA MARIA SANCHEZ DICKSON,COORDINADOR ADMINISTRATIVO,DESPACHO DEL DIRECTOR,77000.0,2209.90,6342.62,2340.80,11816.91,22710.23,54289.77
38,WILDA MARIA CABRAL CARMONA,COORDINADOR TECNICO,DESPACHO DEL DIRECTOR,75000.0,2152.50,6309.35,2280.00,11489.25,22231.10,52768.90
39,PAMELA ELISA PIÑEYRO PELLERANO,ASISTENTE LEGAL,DESPACHO DEL DIRECTOR,75000.0,2152.50,5623.17,2280.00,32166.57,42222.24,32777.76
40,GREGORY MANUEL CONCEPCION POURIET HOLGUIN,AUDITOR,DESPACHO DEL DIRECTOR,75000.0,2152.50,6309.35,2280.00,6636.21,17378.06,57621.94
41,FRANCIS YOLANDA ALBERTINA TAVERAS PICHARDO,ENCARGADO AUDITORIA OPERATIVA,DESPACHO DEL DIRECTOR,72389.0,2077.56,5474.92,2200.63,2018.46,11771.57,60617.43
42,ROSANNA MARIA TORRES DIAZ,ENCARGADO DE AUDITORIA ZONA NORTE,DESPACHO DEL DIRECTOR,72000.0,2066.40,5744.81,2188.80,14764.82,24764.83,47235.17
43,FELIX GABRIEL GARCIA MAÑON,ENCARGADO CONTROL INTERNO,DESPACHO DEL DIRECTOR,72000.0,2066.40,5744.81,2188.80,14152.94,24152.95,47847.05
44,MARGEL LISSELOT EGEL BELLO,ASISTENTE EJECUTIVA I,DESPACHO DEL DIRECTOR,70000.0,2009.00,5368.45,2128.00,17168.30,26673.75,43326.25
45,JOAN ALBERTO CUEVAS CARVAJAL,COORDINADOR DE AUDITORIA,DESPACHO DEL DIRECTOR,70000.0,2009.00,5368.45,2128.00,6806.26,16311.71,53688.29
46,ANGELA ONDINA FERREIRA RODRIGUEZ DE LINARES,AUDITOR,DESPACHO DEL DIRECTOR,70000.0,2009.00,5368.45,2128.00,943.28,10448.73,59551.27
47,DAMARIS ANTONIA HERNANDEZ PAYANO,AUDITOR SENIOR,DESPACHO DEL DIRECTOR,70000.0,2009.00,5368.45,2128.00,16901.02,26406.47,43593.53
48,JUAN RAFAEL GIL ESPINAL,AUDITOR SENIOR,DESPACHO DEL DIRECTOR,70000.0,2009.00,5368.45,2128.00,2855.18,12360.63,57639.37
49,SONIA DOMINGUEZ ALMONTE,COORDINADOR,DESPACHO DEL DIRECTOR,69000.0,1980.30,4837.18,2097.60,4858.34,13773.42,55226.58
50,VIRGINIA LISETTE LOPEZ MEJIA,ANALISTA ADMINISTRATIVO,DESPACHO DEL DIRECTOR,67347.0,1932.86,4869.21,2047.35,23775.54,32624.96,34722.04

In [ ]:
DF_Nomina_Aduanas_NETA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3461 entries, 0 to 3460
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        3461 non-null   object
 1   Cargo_Funcion          3461 non-null   object
 2   Locacion_Departamento  3461 non-null   object
 3   Salario_Bruto          3449 non-null   float64
 4   Descuento_AFP          3449 non-null   float64
 5   Descuento_ISR          3449 non-null   float64
 6   Descuento_SFS          3449 non-null   float64
 7   Otros_Descuentos       3449 non-null   float64
 8   Total_Descuentos       3449 non-null   float64
 9   Salario_Neto           3449 non-null   float64
dtypes: float64(7), object(3)
memory usage: 270.5+ KB

In [ ]:
# 1. Eliminar todas las líneas que contengan al menos 1 o más nulos, nan o NaN
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA.dropna(how='any')

# 2. Eliminar strings vacíos (primero identificamos y luego eliminamos)
# Para cada columna de tipo object, convertimos strings vacíos a NaN
for col in DF_Nomina_Aduanas_NETA.select_dtypes(include='object').columns:
    DF_Nomina_Aduanas_NETA[col] = DF_Nomina_Aduanas_NETA[col].replace('', np.nan)
    # También eliminar strings que solo contienen espacios
    DF_Nomina_Aduanas_NETA[col] = DF_Nomina_Aduanas_NETA[col].replace(r'^\s*$', np.nan, regex=True)

# Eliminar filas que ahora tienen NaN después de convertir strings vacíos
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA.dropna(how='any')

# 3. Eliminar duplicados por "Nombre_Completo" manteniendo el mayor "Salario_Neto"
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA.sort_values('Salario_Neto', ascending=False)
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA.drop_duplicates(subset='Nombre_Completo', keep='first')

# Opcional: Reordenar el índice si lo deseas
DF_Nomina_Aduanas_NETA = DF_Nomina_Aduanas_NETA.reset_index(drop=True)

/tmp/ipython-input-3583781101.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_Nomina_Aduanas_NETA[col] = DF_Nomina_Aduanas_NETA[col].replace('', np.nan)
/tmp/ipython-input-3583781101.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_Nomina_Aduanas_NETA[col] = DF_Nomina_Aduanas_NETA[col].replace(r'^\s*$', np.nan, regex=True)

In [ ]:
DF_Nomina_Aduanas_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EDUARDO JOSE SANZ LOVATON,DIRECTOR GENERAL,DESPACHO DEL DIRECTOR,630919.0,12441.34,140697.34,6589.14,3455.92,163183.74,467735.26
1,ANGEL ALBERTO ENCARNACION AMADOR,SUBDIRECTOR OPERATIVO,SUBDIRECCION OPERATIVA,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
2,DANIEL ARTURO PEÑA FERNANDEZ,SUBDIRECTOR DE TECNOLOGIA,SUBDIRECCION DE TECNOLOGIA,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
3,JUAN BAUTISTA VICENS BELLO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
4,JOANNA MARINA BONNELLY GINEBRA,ASESOR,SUBDIRECCION OPERATIVA,323856.0,9294.67,64718.26,6589.14,3455.92,84057.99,239798.01
...,...,...,...,...,...,...,...,...,...,...
3444,RUBEN CAMILO CUEVAS PEREZ,CHOFER,GERENCIA ADMINISTRATIVA,21916.0,628.99,0.00,666.25,18146.93,19442.17,2473.83
3445,SANDY GALVACIO SANCHEZ,CELADOR,SUBDIRECCION OPERATIVA,16500.0,473.55,0.00,501.60,13085.06,14060.21,2439.79
3446,RAYGLER QUEVEDO PEÑA,CELADOR,SUBDIRECCION OPERATIVA,1650.0,287.00,0.00,304.00,25.00,616.00,1034.00
3447,JOSE RAMON TEJEDA CRUZ,CELADOR,SUBDIRECCION OPERATIVA,1650.0,287.00,0.00,304.00,294.90,885.90,764.10
3448,ARGELIO BENJAMIN MARTINEZ CARIDAD,ASCENSORISTA,SUBDIRECCION ADMINISTRATIVA Y FINANCIERA,29505.0,846.79,0.00,896.95,27668.20,29411.94,93.06

In [ ]:
DF_Nomina_Aduanas_NETA.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EDUARDO JOSE SANZ LOVATON,DIRECTOR GENERAL,DESPACHO DEL DIRECTOR,630919.0,12441.34,140697.34,6589.14,3455.92,163183.74,467735.26
1,ANGEL ALBERTO ENCARNACION AMADOR,SUBDIRECTOR OPERATIVO,SUBDIRECCION OPERATIVA,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
2,DANIEL ARTURO PEÑA FERNANDEZ,SUBDIRECTOR DE TECNOLOGIA,SUBDIRECCION DE TECNOLOGIA,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
3,JUAN BAUTISTA VICENS BELLO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,25.00,81484.80,242371.20
4,JOANNA MARINA BONNELLY GINEBRA,ASESOR,SUBDIRECCION OPERATIVA,323856.0,9294.67,64718.26,6589.14,3455.92,84057.99,239798.01
5,LUCIA YNES ZORRILLA RODRIGUEZ,SUBDIRECTOR GENERAL,SUBDIRECCION GENERAL,323856.0,9294.67,65575.99,6589.14,3225.00,84684.80,239171.20
6,JULIO ANULFO PASCUAL RODRIGUEZ,SUBDIRECTOR DE ZONAS FRANCAS,SUBDIRECCION DE ZONAS FRANCAS,323856.0,9294.67,65147.12,6589.14,6331.32,87362.25,236493.75
7,HANNA LISSET GIL ROSADO,SUPERVISOR REGIONAL,SUBDIRECCION OPERATIVA,323856.0,9294.67,65575.99,6589.14,7386.54,88846.34,235009.66
8,AMADA ALTAGRACIA MENDEZ GUZMAN,GERENTE DE RECURSOS HUMANOS,GERENCIA DE RECURSOS HUMANOS,323856.0,9294.67,65575.99,6589.14,13145.00,94604.80,229251.20
9,OSCAR ORLANDO D'OLEO SEIFFE,GERENTE LEGAL,DESPACHO DEL DIRECTOR,301987.0,8667.03,60265.65,6589.14,25.00,75546.82,226440.18
10,LEIVIN ESENOBEL GUERRERO,ASESOR,DESPACHO DEL DIRECTOR,300000.0,8610.00,59783.15,6589.14,25.00,75007.29,224992.71
11,RAQUEL ELIA SORIANO ABREU,SUBDIRECTOR GENERAL TECNICO,SUBDIRECCION TECNICA,316932.0,9095.95,63465.80,6589.14,12797.31,91948.20,224983.80
12,JUAN VIRGILIO MANSFIELD PEREZ,GERENTE ADMINISTRATIVO,GERENCIA ADMINISTRATIVA,298856.0,8577.17,59505.36,6589.14,25.00,74696.67,224159.33
13,ELIANA MARIA TAVERAS HERRERA,COORDINADOR GENERAL,GERENCIA FINANCIERA,295000.0,8466.50,58569.03,6589.14,25.00,73649.67,221350.33
14,FRANCIS AURELIO ALMONTE RODRIGUEZ,SUBDIRECTOR ADMINISTRATIVO Y FINANC,SUBDIRECCION ADMINISTRATIVA Y FINANCIERA,323856.0,9294.67,65147.12,6589.14,30801.08,111832.01,212023.99
15,EDUARDO LUIS PRESINAL,COORDINADOR DE RELACIONES GUBERNAME,DESPACHO DEL DIRECTOR,300000.0,8610.00,59783.15,6589.14,14131.43,89113.72,210886.28
16,MIGUEL ANTONIO PUENTE LEONOR,GERENTE FINANCIERO,GERENCIA FINANCIERA,300000.0,8610.00,59783.15,6589.14,14725.00,89707.29,210292.71
17,NILKA JOSEFINA DUVERGE MARTINEZ,SUPERVISOR OPERATIVO,SUBDIRECCION OPERATIVA,275000.0,7892.50,53712.53,6589.14,4633.00,72827.17,202172.83
18,ELVYN JOSE GOMEZ PEÑA,COORDINADOR DE TI,SUBDIRECCION DE TECNOLOGIA,265000.0,7605.50,51284.28,6589.14,25.00,65503.92,199496.08
19,JAIR SAMUEL CARABALLO GUILLEN,ENCARGADO DEPARTAMENTO TECNICO DELI,SUBDIRECCION TECNICA,275000.0,7892.50,53712.53,6589.14,11407.26,79601.43,195398.57
20,ANIBELCA MARIA MENA SUSANA,COORDINADOR DEL DESPACHO,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,47381.80,128841.60,195014.40
21,RAINIERO LUIS MARTIN OLIVO BORDAS,ENCARGADO DEPARTAMENTO DE ALMACENES,SUBDIRECCION OPERATIVA,323856.0,9294.67,64718.26,6589.14,48455.92,129057.99,194798.01
22,ALEJANDRO ALBERTO TAVAREZ SAVIÑON,ENCARGADO DEPARTAMENTO DE TRANSPORT,GERENCIA ADMINISTRATIVA,250000.0,7175.00,47641.90,6589.14,1304.00,62710.04,187289.96
23,ALFONSO MANUEL PAULINO GONZALEZ,ENCARGADO DEPARTAMENTO TECNOLOGIAS,SUBDIRECCION DE TECNOLOGIA,250000.0,7175.00,47213.04,6589.14,1740.46,62717.64,187282.36
24,YESSENIA ELIZABETH RODRIGUEZ ESTEVEZ,GERENTE DE SERVICIO AL CONTRIBUYENT,GERENCIA DE ATENCION A GRANDES CONTRIBUYENTES,250000.0,7175.00,47213.04,6589.14,3940.46,64917.64,185082.36
25,MAYRA DEL CARMEN PERERA CALCAÑO,COORDINADOR TECNICO,GERENCIA DE RECURSOS HUMANOS,250000.0,7175.00,47641.90,6589.14,3624.60,65030.64,184969.36
26,RHADAMES CARLOS MANUEL MATEO VARGAS,GERENTE DE AUDITORIA INTERNA,DESPACHO DEL DIRECTOR,250000.0,7175.00,46784.17,6589.14,11480.27,72028.58,177971.42
27,EDUARDO RAMON RODRIGUEZ APOLINARIO,ASESOR,DESPACHO DEL DIRECTOR,323856.0,9294.67,65575.99,6589.14,65933.17,147392.97,176463.03
28,LUIS MATIAS,ADMINISTRADOR OPERATIVO,SUBDIRECCION OPERATIVA,231000.0,6629.70,43028.23,6589.14,1903.00,58150.07,172849.93
29,DEGNIS DANELIS DE LEON BAUTISTA DE VALDEZ,GERENTE DE COMUNICACIONES,GERENCIA DE COMUNICACIONES,275000.0,7892.50,53712.53,6589.14,35156.39,103350.56,171649.44
30,AMAURYS VELEZ DE JESUS,GERENTE DE ANALISIS ECONOMICO,DIRECCION GENERAL,240000.0,6888.00,45213.65,6589.14,10225.00,68915.79,171084.21
31,SANTA MARIANELA MARTE DE LOS SANTOS,GERENTE TECNICO ADUANERO,SUBDIRECCION TECNICA,300000.0,8610.00,59354.29,6589.14,60060.29,134613.72,165386.28
32,ALBA GISELLE GARCIA RUIZ,ENCARGADO DEPARTAMENTO DE INGENIERI,SUBDIRECCION ADMINISTRATIVA Y FINANCIERA,212500.0,6098.75,38568.25,6460.00,4525.00,55652.00,156848.00
33,EDUARDO PASCUAL PALACIOS NUÑEZ,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,232444.0,6671.14,43378.87,6589.14,19225.00,75864.15,156579.85
34,OMAR AMIN TORRES SOTO,ENCARGADO DEPARTAMENTO DE HIDROCARB,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,25.00,47472.94,152527.06
35,NORAH RAQUEL GERMAN GALVEZ,ASISTENTE DEL DIRECTOR,DESPACHO DEL DIRECTOR,200000.0,5740.00,35627.94,6080.00,25.00,47472.94,152527.06
36,RAMON ANTONIO PEÑA CARABALLO,COORDINADOR OPERATIVO ZONA NORTE,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,25.00,47472.94,152527.06
37,MARINELLE MENDOZA MAZARA,ADMINISTRADOR ADUANERO,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,25.00,47472.94,152527.06
38,MARIA ELENA VAZQUEZ GARCIA DE TAVERAS,ADMINISTRADOR ADUANERO,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,25.00,47472.94,152527.06
39,ALEJANDRO GARRIGO LEFELD,COORDINADOR REGIONAL ZONA ESTE,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,844.00,48291.94,151708.06
40,EURY VIDAL SOLANO QUIÑONES,ADMINISTRADOR ADUANERO,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,1180.81,48628.75,151371.25
41,EMMANUEL JOSE ESPINAL,ENCARGADO DIVISION ADUANAS VERDES,GERENCIA DE RECURSOS HUMANOS,200000.0,5740.00,35627.94,6080.00,1304.00,48751.94,151248.06
42,MICHAEL EDUARDO LUGO RISK,REPRESENTANTE DE LA DGA ANTE OTRAS,SUBDIRECCION OPERATIVA,200000.0,5740.00,35199.07,6080.00,2339.46,49358.53,150641.47
43,DEIDANIA SORAYA ESPAILLAT ESPAILLAT,COORDINADOR DE TI,SUBDIRECCION DE TECNOLOGIA,200000.0,5740.00,35627.94,6080.00,2525.00,49972.94,150027.06
44,IVO JOSE GOMEZ LOPEZ-PENHA,GERENTE DE SISTEMAS DE INFORMACION,SUBDIRECCION DE TECNOLOGIA,200000.0,5740.00,35199.07,6080.00,3007.90,50026.97,149973.03
45,REYNALDO ADRIAN GUILAMO PILIER,COORDINADOR GENERAL,DESPACHO DEL DIRECTOR,200000.0,5740.00,35627.94,6080.00,7083.00,54530.94,145469.06
46,AMIN RAFAEL VASQUEZ CASTILLO,COORDINADOR GENERAL,GERENCIA DE FISCALIZACION,200000.0,5740.00,35627.94,6080.00,9025.00,56472.94,143527.06
47,JOSE SOCORRO PEÑA SANTANA,ASESOR,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,10225.00,57672.94,142327.06
48,GADIEL ALBERTO POLANCO PEGUERO,ADMINISTRADOR ADUANERO II (MARITIMO,SUBDIRECCION OPERATIVA,200000.0,5740.00,35627.94,6080.00,11044.00,58491.94,141508.06
49,KAREN ANGELINE RODRIGUEZ LEON,GERENTE DE REGIMENES ESPECIALES,SUBDIRECCION OPERATIVA,200000.0,5740.00,35199.07,6080.00,11940.46,58959.53,141040.47
50,RAFAEL ANTONIO TAPIA PAULINO,ENCARGADO DEPARTAMENTO DE PLANIFICA,GERENCIA DE RECURSOS HUMANOS,187000.0,5366.90,32570.01,5684.80,4285.80,47907.51,139092.49

In [ ]:
DF_Nomina_Aduanas_NETA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3449 entries, 0 to 3448
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        3449 non-null   object
 1   Cargo_Funcion          3449 non-null   object
 2   Locacion_Departamento  3449 non-null   object
 3   Salario_Bruto          3449 non-null   float64
 4   Descuento_AFP          3449 non-null   float64
 5   Descuento_ISR          3449 non-null   float64
 6   Descuento_SFS          3449 non-null   float64
 7   Otros_Descuentos       3449 non-null   float64
 8   Total_Descuentos       3449 non-null   float64
 9   Salario_Neto           3449 non-null   float64
dtypes: float64(7), object(3)
memory usage: 269.6+ KB

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

In [ ]:
DF_Nomina_MedioAmbiente_Bruto = pd.read_csv("MedioAmbiente_Nomina.csv")

In [ ]:
DF_Nomina_MedioAmbiente_Bruto

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,DIRECCION DE RECURSOS HUMANOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RELACION NOMINA PERSONAL FIJO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NOMINA MES OCTUBRE 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NO,NOMBRES Y APELLIDOS,CARGO,TIPO DE EMPLEADO,GENERO,SUELDO,AFP,ISR,SFS,OTROS DESC,TOTAL DESC.,NETO
...,...,...,...,...,...,...,...,...,...,...,...,...
3302,3115,CRIS YANILL RODRIGUEZ REYNOSO,MENSAJERO INTERNO,FIJO,FEMENINO,"25,000.00",692.78,7.70,758.91,725.11,"1,869.83","23,136.04"
3303,NaN,DIVISION DE HABILITACION Y SEGUIMIENTO A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3304,3116,LAURA PATRICIA RODRIGUEZ PEÑA,ENCARGADO (A),FIJO,FEMENINO,"95,000.00","2,701.78","10,936.94","2,863.91","2,650.11","18,986.07","75,995.80"
3305,NaN,TOTAL,NaN,NaN,NaN,"92,823,261.15","2,663,931.97","3,560,257.65","2,810,183.80","8,072,942.33","17,107,417.31","75,715,843.62"
3306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_MedioAmbiente_Bruto.head(51)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,DIRECCION DE RECURSOS HUMANOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RELACION NOMINA PERSONAL FIJO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NOMINA MES OCTUBRE 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NO,NOMBRES Y APELLIDOS,CARGO,TIPO DE EMPLEADO,GENERO,SUELDO,AFP,ISR,SFS,OTROS DESC,TOTAL DESC.,NETO
5,NaN,DESPACHO DEL MINISTRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,ARMANDO PAINO HENRIQUEZ DAJER,MINISTRO (A),FIJO,MASCULINO,"300,000.00","8,585.28","59,790.78","6,588.05",10700.11,"85,474.55","214,531.32"
7,2,ISIDRO ARAUJO ROMERO,COORDINADOR (A),FIJO,MASCULINO,"75,000.00","2,127.78","6,317.08","2,278.91",0.00,"11,134.21","63,871.66"
8,3,JHON ELICH GRULLON VALDEZ,ASISTENTE,FIJO,MASCULINO,"90,000.00","2,558.28","9,331.95","2,734.91",0.00,"16,751.04","73,254.83"
9,4,JULISSA MARIAM RAFUL RUIZ,ASESOR (A),FIJO,FEMENINO,"200,000.00","5,715.28","35,635.57","6,078.91",0.00,"47,840.20","152,165.67"
10,5,HENRY JULIAN DISLA PERALTA,ASESOR (A),FIJO,MASCULINO,"100,000.00","2,845.28","11,255.34","3,038.91",0.00,"20,980.89","79,024.98"
11,6,VICTOR JIMENEZ VASQUEZ,ANALISTA DE GESTION,FIJO,MASCULINO,"60,000.00","1,697.28","3,494.38","1,822.91",1602.54,"8,427.44","51,578.43"
12,7,ROCHELA PAOLA MONTAS RODRIGUEZ,ASISTENTE,FIJO,FEMENINO,"140,000.00","3,993.28","21,522.07","4,254.91",725.11,"30,180.70","110,151.42"
13,8,ANTONIO CARLOS TRONCOSO JIMENEZ,ASESOR,FIJO,MASCULINO,"100,000.00","2,845.28","12,113.07","3,038.91",725.11,"18,407.70","81,924.42"
14,9,MARIA BERTHA BATLLE MANUKYAN,ASESOR (A),FIJO,FEMENINO,"100,000.00","2,845.28","12,113.07","3,038.91",400.11,"18,407.70","81,598.17"
15,10,PAMELA ADALGISA GONZALEZ ZORRILLA,ASISTENTE DE DESPACHO,FIJO,FEMENINO,"140,000.00","3,993.28","21,522.07","4,254.91",7857.91,"37,438.50","102,567.37"
16,11,MAIRENY INFANTE TAVERAS,ASESOR (A),FIJO,FEMENINO,"200,000.00","5,715.28","35,635.57","6,078.91",600.11,"47,840.20","152,165.67"
17,12,FRANCISCO JOSE TOBIAS BORDAS CASTELLANOS,ASESOR (A),FIJO,MASCULINO,"200,000.00","5,715.28","35,635.57","6,078.91",600.11,"47,840.20","152,165.67"
18,13,SIMON TADEO PERALTA DAVID,ASISTENTE PERSONAL,FIJO,MASCULINO,"75,000.00","2,127.78","6,317.08","2,278.91",600.11,"11,134.21","63,871.66"
19,14,MARIO ANDRE FRANCO DE JESUS,ASESOR (A),FIJO,MASCULINO,"200,000.00","5,715.28","35,635.57","6,078.91",600.11,"47,840.20","152,165.67"
20,15,ENRIQUE BIENVENIDO MARCHENA,ASESOR,FIJO,MASCULINO,"140,000.00","3,993.28","21,522.07","4,254.91",600.11,"30,180.70","109,825.17"
21,16,WINNYFER SANCHEZ ABREU,ASISTENTE,FIJO,FEMENINO,"100,000.00","2,845.28","11,255.34","3,038.91",600.11,"20,980.89","79,024.98"
22,17,JOSE MANUEL MATEO FELIZ,ASESOR,FIJO,MASCULINO,"185,000.00","5,284.78","32,107.19","5,622.91","7,235.06","50,060.27","134,945.60"
23,18,FELICITA SORIANO CASTRO,AUXILIAR,FIJO,FEMENINO,"30,000.00",836.28,7.70,910.91,967.59,"2,532.81","27,473.06"
24,19,JOEL HOMERO GOMEZ VICTORERO,ASESOR (A),FIJO,MASCULINO,"200,000.00","5,715.28","20,504.31","6,078.91","18,216.11","50,324.94","149,680.93"
25,20,JEAN PAUL CARTAGENA ABREU,ASISTENTE DEL DESPACHO,FIJO,MASCULINO,"140,000.00","3,993.28","21,522.07","4,254.91","2,414.55","31,995.14","108,010.73"
26,21,RAMONA MARLENIS GUILLEN CIPRIAN,ASISTENTE EJECUTIVA,FIJO,FEMENINO,"140,000.00","3,993.28","21,522.07","4,254.91","1,668.51","31,249.10","108,756.77"
27,22,JOSE LUIS LEDESMA TERRERO,ASESOR (A),FIJO,MASCULINO,"140,000.00","3,993.28","21,522.07","4,254.91",600.11,"30,180.70","109,825.17"
28,NaN,VICEMINISTERIO DE GESTION AMBIENTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,23,LENIN RAMON BUENO RODRIGUEZ,VICEMINISTRO (A),FIJO,MASCULINO,"257,500.00","7,365.53","49,470.72","6,588.05",600.11,"63,834.74","193,671.13"
30,24,JAVIER HERNANDEZ JIMENEZ,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,"4,475.74","5,745.46","19,260.41"
31,25,ALFONSO MIGUEL DURAN ALMONTE,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,"12,578.01","13,847.73","22,086.04"
32,26,DANILO SANCHEZ,CHOFER I,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,650.11,"1,919.83","23,086.04"
33,27,ELIGIO DE OLEO,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,"3,285.06","4,554.78","20,451.09"
34,28,WENDY JARISSIE ESTRADA ARES,ASISTENTE EJECUTIVA,FIJO,FEMENINO,"70,000.00","1,984.28",7.70,"2,126.91","2,249.62","6,178.84","63,827.03"
35,29,JHONNY FERNANDO SALDAÑA VALDEZ,SOPORTE ADMINISTRATIVO,FIJO,MASCULINO,"55,000.00","1,553.78","2,567.38","1,670.91","9,765.47","15,367.87","39,638.00"
36,30,FRANCISCO ALBERTO VALDEZ VILLA FAÑA,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,600.11,"1,869.83","23,136.04"
37,31,WENDY ROSARIO,AUXILIAR ADMINISTRATIVO (A),FIJO,FEMENINO,"40,000.00","1,123.28",450.35,"1,214.91",650.11,"3,248.98","36,756.89"
38,32,LUCIANO FELIZ,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,"2,995.29","4,265.01","20,740.86"
39,33,JATNA YUNARYS DE LEON DE LA CRUZ,ANALISTA GESTION AMBIENTAL,FIJO,FEMENINO,"60,000.00",1697.28,3494.38,1822.91,"5,567.59","12,392.49","47,613.38"
40,34,YHONATAN LEONEL SEVERINO,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,600.11,"1,869.83","23,136.04"
41,35,WASCAR ODALIX GONZALEZ BAEZ,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,"7,301.37","8,571.09","16,434.78"
42,36,LUIS MANUEL JOAQUIN MOREL,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,650.11,"1,919.83","23,086.04"
43,37,CAISAR ARBAJE SIDO,ASESOR,FIJO,MASCULINO,"100,000.00","2,845.28",12113.07,"3,038.91","7,600.11","25,407.70","74,598.17"
44,38,LUIS JOSE GARCIA ABREU,SOPORTE ADMINISTRATIVO,FIJO,MASCULINO,"45,000.00","1,266.78",1156.03,"1,366.91","10,335.73","13,935.78","31,070.09"
45,39,ELIANA ISABEL LEON GUZMAN,ASISTENTE,FIJO,FEMENINO,"90,000.00","2,558.28",9760.82,"2,734.91",600.11,"15,464.45","74,541.42"
46,40,FEDERICO DE LEON TAVAREZ,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,"10,316.68","11,586.40","13,419.47"
47,41,ANTONIO GONZALEZ POLANCO,CHOFER,FIJO,MASCULINO,"25,000.00",692.78,7.70,758.91,725.11,"1,869.83","23,136.04"
48,42,CARLOS MANUEL POLANCO MEJIA,CHOFER,FIJO,MASCULINO,"30,000.00",836.28,7.70,910.91,600.11,"2,165.33","27,840.54"
49,43,CINTHIA CELESTE AQUINO PIÑEIRO,AUXILIAR ADMINISTRATIVO I,FIJO,FEMENINO,"40,000.00","1,123.28",450.35,"1,214.91","6,601.38","9,200.25","30,805.62"
50,44,ZOILO MENDOZA RINCON,CHOFER,FIJO,MASCULINO,"35,000.00",979.78,7.70,"1,062.91","7,037.23","8,897.95","26,107.92"

In [ ]:
DF_Nomina_MedioAmbiente_Bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3307 entries, 0 to 3306
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   3112 non-null   object
 1   Unnamed: 1   3302 non-null   object
 2   Unnamed: 2   3117 non-null   object
 3   Unnamed: 3   3117 non-null   object
 4   Unnamed: 4   3117 non-null   object
 5   Unnamed: 5   3118 non-null   object
 6   Unnamed: 6   3118 non-null   object
 7   Unnamed: 7   3118 non-null   object
 8   Unnamed: 8   3118 non-null   object
 9   Unnamed: 9   3118 non-null   object
 10  Unnamed: 10  3118 non-null   object
 11  Unnamed: 11  3118 non-null   object
dtypes: object(12)
memory usage: 310.2+ KB

In [ ]:
# Crear una copia del DataFrame original para trabajar
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_Bruto.copy()

# 1. Filtrar solo las filas que tienen datos de empleados (filas con números en la primera columna)
# Convertir la primera columna a numérico donde sea posible
DF_Nomina_MedioAmbiente_NETA['Unnamed: 0'] = pd.to_numeric(DF_Nomina_MedioAmbiente_NETA['Unnamed: 0'], errors='coerce')

# Filtrar solo las filas donde la primera columna es numérica (son los registros de empleados)
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA[DF_Nomina_MedioAmbiente_NETA['Unnamed: 0'].notna()]

# 2. Seleccionar y renombrar las columnas necesarias
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA.rename(columns={
    'Unnamed: 1': 'Nombre_Completo',
    'Unnamed: 2': 'Cargo_Funcion',
    'Unnamed: 5': 'Salario_Bruto',
    'Unnamed: 6': 'Descuento_AFP',
    'Unnamed: 7': 'Descuento_ISR',
    'Unnamed: 8': 'Descuento_SFS',
    'Unnamed: 9': 'Otros_Descuentos',
    'Unnamed: 10': 'Total_Descuentos',
    'Unnamed: 11': 'Salario_Neto'
})

# 3. Crear la columna Locacion_Departamento con el valor constante
DF_Nomina_MedioAmbiente_NETA['Locacion_Departamento'] = 'Ministerio de Medio Ambiente'

# 4. Seleccionar solo las columnas que necesitamos en el orden correcto
columnas_necesarias = [
    'Nombre_Completo',
    'Cargo_Funcion',
    'Locacion_Departamento',
    'Salario_Bruto',
    'Descuento_AFP',
    'Descuento_ISR',
    'Descuento_SFS',
    'Otros_Descuentos',
    'Total_Descuentos',
    'Salario_Neto'
]

DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA[columnas_necesarias]

# 5. Convertir las columnas numéricas a float64
# Primero, limpiar los valores numéricos (eliminar comas y espacios)
columnas_numericas = ['Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
                      'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']

for col in columnas_numericas:
    # Convertir a string, eliminar comas y espacios, luego a float
    DF_Nomina_MedioAmbiente_NETA[col] = DF_Nomina_MedioAmbiente_NETA[col].astype(str).str.replace(',', '').str.strip()
    DF_Nomina_MedioAmbiente_NETA[col] = pd.to_numeric(DF_Nomina_MedioAmbiente_NETA[col], errors='coerce')

# 6. Convertir las columnas de texto a object (string)
columnas_texto = ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento']
for col in columnas_texto:
    DF_Nomina_MedioAmbiente_NETA[col] = DF_Nomina_MedioAmbiente_NETA[col].astype('object')

In [ ]:
DF_Nomina_MedioAmbiente_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
6,ARMANDO PAINO HENRIQUEZ DAJER,MINISTRO (A),Ministerio de Medio Ambiente,300000.0,8585.28,59790.78,6588.05,10700.11,85474.55,214531.32
7,ISIDRO ARAUJO ROMERO,COORDINADOR (A),Ministerio de Medio Ambiente,75000.0,2127.78,6317.08,2278.91,0.00,11134.21,63871.66
8,JHON ELICH GRULLON VALDEZ,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9331.95,2734.91,0.00,16751.04,73254.83
9,JULISSA MARIAM RAFUL RUIZ,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,0.00,47840.20,152165.67
10,HENRY JULIAN DISLA PERALTA,ASESOR (A),Ministerio de Medio Ambiente,100000.0,2845.28,11255.34,3038.91,0.00,20980.89,79024.98
...,...,...,...,...,...,...,...,...,...,...
3299,DENIA LOURDES CAIRO PINEDA,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,600.11,3198.98,36806.89
3300,KATHERINE ARIDELSI GOMEZ DE LA CRUZ,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,650.11,3248.98,36756.89
3301,KIARA ABRIL MATEO QUEZADA,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,600.11,3198.98,36806.89
3302,CRIS YANILL RODRIGUEZ REYNOSO,MENSAJERO INTERNO,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,725.11,1869.83,23136.04
3304,LAURA PATRICIA RODRIGUEZ PEÑA,ENCARGADO (A),Ministerio de Medio Ambiente,95000.0,2701.78,10936.94,2863.91,2650.11,18986.07,75995.80

In [ ]:
DF_Nomina_MedioAmbiente_NETA.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
6,ARMANDO PAINO HENRIQUEZ DAJER,MINISTRO (A),Ministerio de Medio Ambiente,300000.0,8585.28,59790.78,6588.05,10700.11,85474.55,214531.32
7,ISIDRO ARAUJO ROMERO,COORDINADOR (A),Ministerio de Medio Ambiente,75000.0,2127.78,6317.08,2278.91,0.00,11134.21,63871.66
8,JHON ELICH GRULLON VALDEZ,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9331.95,2734.91,0.00,16751.04,73254.83
9,JULISSA MARIAM RAFUL RUIZ,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,0.00,47840.20,152165.67
10,HENRY JULIAN DISLA PERALTA,ASESOR (A),Ministerio de Medio Ambiente,100000.0,2845.28,11255.34,3038.91,0.00,20980.89,79024.98
11,VICTOR JIMENEZ VASQUEZ,ANALISTA DE GESTION,Ministerio de Medio Ambiente,60000.0,1697.28,3494.38,1822.91,1602.54,8427.44,51578.43
12,ROCHELA PAOLA MONTAS RODRIGUEZ,ASISTENTE,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,725.11,30180.70,110151.42
13,ANTONIO CARLOS TRONCOSO JIMENEZ,ASESOR,Ministerio de Medio Ambiente,100000.0,2845.28,12113.07,3038.91,725.11,18407.70,81924.42
14,MARIA BERTHA BATLLE MANUKYAN,ASESOR (A),Ministerio de Medio Ambiente,100000.0,2845.28,12113.07,3038.91,400.11,18407.70,81598.17
15,PAMELA ADALGISA GONZALEZ ZORRILLA,ASISTENTE DE DESPACHO,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,7857.91,37438.50,102567.37
16,MAIRENY INFANTE TAVERAS,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,600.11,47840.20,152165.67
17,FRANCISCO JOSE TOBIAS BORDAS CASTELLANOS,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,600.11,47840.20,152165.67
18,SIMON TADEO PERALTA DAVID,ASISTENTE PERSONAL,Ministerio de Medio Ambiente,75000.0,2127.78,6317.08,2278.91,600.11,11134.21,63871.66
19,MARIO ANDRE FRANCO DE JESUS,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,600.11,47840.20,152165.67
20,ENRIQUE BIENVENIDO MARCHENA,ASESOR,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,600.11,30180.70,109825.17
21,WINNYFER SANCHEZ ABREU,ASISTENTE,Ministerio de Medio Ambiente,100000.0,2845.28,11255.34,3038.91,600.11,20980.89,79024.98
22,JOSE MANUEL MATEO FELIZ,ASESOR,Ministerio de Medio Ambiente,185000.0,5284.78,32107.19,5622.91,7235.06,50060.27,134945.60
23,FELICITA SORIANO CASTRO,AUXILIAR,Ministerio de Medio Ambiente,30000.0,836.28,7.70,910.91,967.59,2532.81,27473.06
24,JOEL HOMERO GOMEZ VICTORERO,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,20504.31,6078.91,18216.11,50324.94,149680.93
25,JEAN PAUL CARTAGENA ABREU,ASISTENTE DEL DESPACHO,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,2414.55,31995.14,108010.73
26,RAMONA MARLENIS GUILLEN CIPRIAN,ASISTENTE EJECUTIVA,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,1668.51,31249.10,108756.77
27,JOSE LUIS LEDESMA TERRERO,ASESOR (A),Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,600.11,30180.70,109825.17
29,LENIN RAMON BUENO RODRIGUEZ,VICEMINISTRO (A),Ministerio de Medio Ambiente,257500.0,7365.53,49470.72,6588.05,600.11,63834.74,193671.13
30,JAVIER HERNANDEZ JIMENEZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,4475.74,5745.46,19260.41
31,ALFONSO MIGUEL DURAN ALMONTE,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,12578.01,13847.73,22086.04
32,DANILO SANCHEZ,CHOFER I,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,650.11,1919.83,23086.04
33,ELIGIO DE OLEO,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,3285.06,4554.78,20451.09
34,WENDY JARISSIE ESTRADA ARES,ASISTENTE EJECUTIVA,Ministerio de Medio Ambiente,70000.0,1984.28,7.70,2126.91,2249.62,6178.84,63827.03
35,JHONNY FERNANDO SALDAÑA VALDEZ,SOPORTE ADMINISTRATIVO,Ministerio de Medio Ambiente,55000.0,1553.78,2567.38,1670.91,9765.47,15367.87,39638.00
36,FRANCISCO ALBERTO VALDEZ VILLA FAÑA,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,600.11,1869.83,23136.04
37,WENDY ROSARIO,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,650.11,3248.98,36756.89
38,LUCIANO FELIZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,2995.29,4265.01,20740.86
39,JATNA YUNARYS DE LEON DE LA CRUZ,ANALISTA GESTION AMBIENTAL,Ministerio de Medio Ambiente,60000.0,1697.28,3494.38,1822.91,5567.59,12392.49,47613.38
40,YHONATAN LEONEL SEVERINO,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,600.11,1869.83,23136.04
41,WASCAR ODALIX GONZALEZ BAEZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,7301.37,8571.09,16434.78
42,LUIS MANUEL JOAQUIN MOREL,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,650.11,1919.83,23086.04
43,CAISAR ARBAJE SIDO,ASESOR,Ministerio de Medio Ambiente,100000.0,2845.28,12113.07,3038.91,7600.11,25407.70,74598.17
44,LUIS JOSE GARCIA ABREU,SOPORTE ADMINISTRATIVO,Ministerio de Medio Ambiente,45000.0,1266.78,1156.03,1366.91,10335.73,13935.78,31070.09
45,ELIANA ISABEL LEON GUZMAN,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9760.82,2734.91,600.11,15464.45,74541.42
46,FEDERICO DE LEON TAVAREZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,10316.68,11586.40,13419.47
47,ANTONIO GONZALEZ POLANCO,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,725.11,1869.83,23136.04
48,CARLOS MANUEL POLANCO MEJIA,CHOFER,Ministerio de Medio Ambiente,30000.0,836.28,7.70,910.91,600.11,2165.33,27840.54
49,CINTHIA CELESTE AQUINO PIÑEIRO,AUXILIAR ADMINISTRATIVO I,Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,6601.38,9200.25,30805.62
50,ZOILO MENDOZA RINCON,CHOFER,Ministerio de Medio Ambiente,35000.0,979.78,7.70,1062.91,7037.23,8897.95,26107.92
51,PEDRO ANTONIO PERALTA GONZALEZ,ASISTENTE,Ministerio de Medio Ambiente,150000.0,4280.28,23874.32,4558.91,600.11,33123.95,116881.92
52,LOURDES YRENE FERNANDEZ LOPEZ,ASESOR (A),Ministerio de Medio Ambiente,150000.0,4280.28,23874.32,4558.91,4279.00,36802.84,113203.03
53,JUDITH ZARINA DE JESUS MORDAN,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9760.82,2734.91,600.11,15464.45,74541.42
54,HUMBERTO ANTONIO INOA,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,650.11,1919.83,23086.04
55,RAMONA LIDIBERT GONZALEZ GONZALEZ,ASESOR,Ministerio de Medio Ambiente,185000.0,5284.78,32107.19,5622.91,13934.15,56759.36,128246.51
57,FRAQUIN OCLIDES PEÑA PEREZ,TECNICO,Ministerio de Medio Ambiente,35000.0,979.78,7.70,1062.91,6617.37,10193.55,24812.32
58,RAMON ANTONIO CANDELARIO BRITO,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,35000.0,979.78,7.70,1062.91,600.11,2460.83,32545.04

In [ ]:
DF_Nomina_MedioAmbiente_NETA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3107 entries, 6 to 3304
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        3107 non-null   object
 1   Cargo_Funcion          3107 non-null   object
 2   Locacion_Departamento  3107 non-null   object
 3   Salario_Bruto          3107 non-null   float64
 4   Descuento_AFP          3107 non-null   float64
 5   Descuento_ISR          3107 non-null   float64
 6   Descuento_SFS          3107 non-null   float64
 7   Otros_Descuentos       3107 non-null   float64
 8   Total_Descuentos       3107 non-null   float64
 9   Salario_Neto           3107 non-null   float64
dtypes: float64(7), object(3)
memory usage: 267.0+ KB

In [ ]:
# Paso 1: Eliminar todas las líneas que contengan al menos 1 o más valores nulos (NaN)
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA.dropna()

# Paso 2: Eliminar strings vacíos en todas las columnas de texto
columnas_texto = DF_Nomina_MedioAmbiente_NETA.select_dtypes(include=['object']).columns
for col in columnas_texto:
    DF_Nomina_MedioAmbiente_NETA[col] = DF_Nomina_MedioAmbiente_NETA[col].replace(r'^\s*$', np.nan, regex=True)

DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA.dropna(subset=columnas_texto)

# Paso 3: Eliminar duplicados por "Nombre_Completo", conservando la fila con mayor "Salario_Neto"
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA.sort_values('Salario_Neto', ascending=False)
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA.drop_duplicates(subset=['Nombre_Completo'], keep='first')

# Restaurar el orden original (basado en el índice original)
DF_Nomina_MedioAmbiente_NETA = DF_Nomina_MedioAmbiente_NETA.sort_index()

In [ ]:
DF_Nomina_MedioAmbiente_NETA

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
6,ARMANDO PAINO HENRIQUEZ DAJER,MINISTRO (A),Ministerio de Medio Ambiente,300000.0,8585.28,59790.78,6588.05,10700.11,85474.55,214531.32
7,ISIDRO ARAUJO ROMERO,COORDINADOR (A),Ministerio de Medio Ambiente,75000.0,2127.78,6317.08,2278.91,0.00,11134.21,63871.66
8,JHON ELICH GRULLON VALDEZ,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9331.95,2734.91,0.00,16751.04,73254.83
9,JULISSA MARIAM RAFUL RUIZ,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,0.00,47840.20,152165.67
10,HENRY JULIAN DISLA PERALTA,ASESOR (A),Ministerio de Medio Ambiente,100000.0,2845.28,11255.34,3038.91,0.00,20980.89,79024.98
...,...,...,...,...,...,...,...,...,...,...
3299,DENIA LOURDES CAIRO PINEDA,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,600.11,3198.98,36806.89
3300,KATHERINE ARIDELSI GOMEZ DE LA CRUZ,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,650.11,3248.98,36756.89
3301,KIARA ABRIL MATEO QUEZADA,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,600.11,3198.98,36806.89
3302,CRIS YANILL RODRIGUEZ REYNOSO,MENSAJERO INTERNO,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,725.11,1869.83,23136.04
3304,LAURA PATRICIA RODRIGUEZ PEÑA,ENCARGADO (A),Ministerio de Medio Ambiente,95000.0,2701.78,10936.94,2863.91,2650.11,18986.07,75995.80

In [ ]:
DF_Nomina_MedioAmbiente_NETA.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
6,ARMANDO PAINO HENRIQUEZ DAJER,MINISTRO (A),Ministerio de Medio Ambiente,300000.0,8585.28,59790.78,6588.05,10700.11,85474.55,214531.32
7,ISIDRO ARAUJO ROMERO,COORDINADOR (A),Ministerio de Medio Ambiente,75000.0,2127.78,6317.08,2278.91,0.00,11134.21,63871.66
8,JHON ELICH GRULLON VALDEZ,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9331.95,2734.91,0.00,16751.04,73254.83
9,JULISSA MARIAM RAFUL RUIZ,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,0.00,47840.20,152165.67
10,HENRY JULIAN DISLA PERALTA,ASESOR (A),Ministerio de Medio Ambiente,100000.0,2845.28,11255.34,3038.91,0.00,20980.89,79024.98
11,VICTOR JIMENEZ VASQUEZ,ANALISTA DE GESTION,Ministerio de Medio Ambiente,60000.0,1697.28,3494.38,1822.91,1602.54,8427.44,51578.43
12,ROCHELA PAOLA MONTAS RODRIGUEZ,ASISTENTE,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,725.11,30180.70,110151.42
13,ANTONIO CARLOS TRONCOSO JIMENEZ,ASESOR,Ministerio de Medio Ambiente,100000.0,2845.28,12113.07,3038.91,725.11,18407.70,81924.42
14,MARIA BERTHA BATLLE MANUKYAN,ASESOR (A),Ministerio de Medio Ambiente,100000.0,2845.28,12113.07,3038.91,400.11,18407.70,81598.17
15,PAMELA ADALGISA GONZALEZ ZORRILLA,ASISTENTE DE DESPACHO,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,7857.91,37438.50,102567.37
16,MAIRENY INFANTE TAVERAS,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,600.11,47840.20,152165.67
17,FRANCISCO JOSE TOBIAS BORDAS CASTELLANOS,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,600.11,47840.20,152165.67
18,SIMON TADEO PERALTA DAVID,ASISTENTE PERSONAL,Ministerio de Medio Ambiente,75000.0,2127.78,6317.08,2278.91,600.11,11134.21,63871.66
19,MARIO ANDRE FRANCO DE JESUS,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,35635.57,6078.91,600.11,47840.20,152165.67
20,ENRIQUE BIENVENIDO MARCHENA,ASESOR,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,600.11,30180.70,109825.17
21,WINNYFER SANCHEZ ABREU,ASISTENTE,Ministerio de Medio Ambiente,100000.0,2845.28,11255.34,3038.91,600.11,20980.89,79024.98
22,JOSE MANUEL MATEO FELIZ,ASESOR,Ministerio de Medio Ambiente,185000.0,5284.78,32107.19,5622.91,7235.06,50060.27,134945.60
23,FELICITA SORIANO CASTRO,AUXILIAR,Ministerio de Medio Ambiente,30000.0,836.28,7.70,910.91,967.59,2532.81,27473.06
24,JOEL HOMERO GOMEZ VICTORERO,ASESOR (A),Ministerio de Medio Ambiente,200000.0,5715.28,20504.31,6078.91,18216.11,50324.94,149680.93
25,JEAN PAUL CARTAGENA ABREU,ASISTENTE DEL DESPACHO,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,2414.55,31995.14,108010.73
26,RAMONA MARLENIS GUILLEN CIPRIAN,ASISTENTE EJECUTIVA,Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,1668.51,31249.10,108756.77
27,JOSE LUIS LEDESMA TERRERO,ASESOR (A),Ministerio de Medio Ambiente,140000.0,3993.28,21522.07,4254.91,600.11,30180.70,109825.17
29,LENIN RAMON BUENO RODRIGUEZ,VICEMINISTRO (A),Ministerio de Medio Ambiente,257500.0,7365.53,49470.72,6588.05,600.11,63834.74,193671.13
30,JAVIER HERNANDEZ JIMENEZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,4475.74,5745.46,19260.41
31,ALFONSO MIGUEL DURAN ALMONTE,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,12578.01,13847.73,22086.04
32,DANILO SANCHEZ,CHOFER I,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,650.11,1919.83,23086.04
33,ELIGIO DE OLEO,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,3285.06,4554.78,20451.09
34,WENDY JARISSIE ESTRADA ARES,ASISTENTE EJECUTIVA,Ministerio de Medio Ambiente,70000.0,1984.28,7.70,2126.91,2249.62,6178.84,63827.03
35,JHONNY FERNANDO SALDAÑA VALDEZ,SOPORTE ADMINISTRATIVO,Ministerio de Medio Ambiente,55000.0,1553.78,2567.38,1670.91,9765.47,15367.87,39638.00
36,FRANCISCO ALBERTO VALDEZ VILLA FAÑA,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,600.11,1869.83,23136.04
37,WENDY ROSARIO,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,650.11,3248.98,36756.89
38,LUCIANO FELIZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,2995.29,4265.01,20740.86
39,JATNA YUNARYS DE LEON DE LA CRUZ,ANALISTA GESTION AMBIENTAL,Ministerio de Medio Ambiente,60000.0,1697.28,3494.38,1822.91,5567.59,12392.49,47613.38
40,YHONATAN LEONEL SEVERINO,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,600.11,1869.83,23136.04
41,WASCAR ODALIX GONZALEZ BAEZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,7301.37,8571.09,16434.78
42,LUIS MANUEL JOAQUIN MOREL,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,650.11,1919.83,23086.04
43,CAISAR ARBAJE SIDO,ASESOR,Ministerio de Medio Ambiente,100000.0,2845.28,12113.07,3038.91,7600.11,25407.70,74598.17
44,LUIS JOSE GARCIA ABREU,SOPORTE ADMINISTRATIVO,Ministerio de Medio Ambiente,45000.0,1266.78,1156.03,1366.91,10335.73,13935.78,31070.09
45,ELIANA ISABEL LEON GUZMAN,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9760.82,2734.91,600.11,15464.45,74541.42
46,FEDERICO DE LEON TAVAREZ,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,10316.68,11586.40,13419.47
47,ANTONIO GONZALEZ POLANCO,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,725.11,1869.83,23136.04
48,CARLOS MANUEL POLANCO MEJIA,CHOFER,Ministerio de Medio Ambiente,30000.0,836.28,7.70,910.91,600.11,2165.33,27840.54
49,CINTHIA CELESTE AQUINO PIÑEIRO,AUXILIAR ADMINISTRATIVO I,Ministerio de Medio Ambiente,40000.0,1123.28,450.35,1214.91,6601.38,9200.25,30805.62
50,ZOILO MENDOZA RINCON,CHOFER,Ministerio de Medio Ambiente,35000.0,979.78,7.70,1062.91,7037.23,8897.95,26107.92
51,PEDRO ANTONIO PERALTA GONZALEZ,ASISTENTE,Ministerio de Medio Ambiente,150000.0,4280.28,23874.32,4558.91,600.11,33123.95,116881.92
52,LOURDES YRENE FERNANDEZ LOPEZ,ASESOR (A),Ministerio de Medio Ambiente,150000.0,4280.28,23874.32,4558.91,4279.00,36802.84,113203.03
53,JUDITH ZARINA DE JESUS MORDAN,ASISTENTE,Ministerio de Medio Ambiente,90000.0,2558.28,9760.82,2734.91,600.11,15464.45,74541.42
54,HUMBERTO ANTONIO INOA,CHOFER,Ministerio de Medio Ambiente,25000.0,692.78,7.70,758.91,650.11,1919.83,23086.04
55,RAMONA LIDIBERT GONZALEZ GONZALEZ,ASESOR,Ministerio de Medio Ambiente,185000.0,5284.78,32107.19,5622.91,13934.15,56759.36,128246.51
57,FRAQUIN OCLIDES PEÑA PEREZ,TECNICO,Ministerio de Medio Ambiente,35000.0,979.78,7.70,1062.91,6617.37,10193.55,24812.32
58,RAMON ANTONIO CANDELARIO BRITO,AUXILIAR ADMINISTRATIVO (A),Ministerio de Medio Ambiente,35000.0,979.78,7.70,1062.91,600.11,2460.83,32545.04

In [ ]:
DF_Nomina_MedioAmbiente_NETA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3107 entries, 6 to 3304
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        3107 non-null   object
 1   Cargo_Funcion          3107 non-null   object
 2   Locacion_Departamento  3107 non-null   object
 3   Salario_Bruto          3107 non-null   float64
 4   Descuento_AFP          3107 non-null   float64
 5   Descuento_ISR          3107 non-null   float64
 6   Descuento_SFS          3107 non-null   float64
 7   Otros_Descuentos       3107 non-null   float64
 8   Total_Descuentos       3107 non-null   float64
 9   Salario_Neto           3107 non-null   float64
dtypes: float64(7), object(3)
memory usage: 267.0+ KB

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

In [ ]:
DF_Nomina_ImpuestosInternos_Bruto = pd.read_csv("ImpuestosInternos_Nomina.csv")

In [ ]:
DF_Nomina_ImpuestosInternos_Bruto

,Unnamed: 0,PERSONAL NOMBRADO\nOCTUBRE 2025,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3044,Raqueline Peña Amaro\nGerente de Recursos Humanos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DF_Nomina_ImpuestosInternos_Bruto.head(51)

,Unnamed: 0,PERSONAL NOMBRADO\nOCTUBRE 2025,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Nombre (s) y Apellido (s),Genero,Cargos,Area,Estatus,Tipo Empleados,Salario Bruto\n(RD$),ISR\n(Ley 11-92,Seguridad Social (Ley 87-01),NaN,Otros\nDescuentos,Salario Neto\n(RD$)
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seguro de Pension,Seguro de Salud,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Empleado\n(2.87%),Empleado\n(3.04%),NaN,NaN
8,EFRAIN EVANGELISTA DIAZ,masculino,Encargado de Compras Menores y Directas,Sección Compras Menores y Directas,Activo,Fijo,"112,438.00","15,031.16","3,226.97","3,418.12","1,963.66","88,798.09"
9,MARTIN ALBERTO GOMEZ MARTINEZ,masculino,Encargado de Departamento C Protocolo,Departamento de Protocolo,Activo,Fijo,"153,149.00","24,178.54","4,395.38","4,655.73","10,704.18","109,215.17"
10,ROSA ANNETTE SEGURA VARGAS,femenino,Secretaria B,Departamento de Seguridad de la Informac,Activo,Fijo,"41,278.00",365.70,"1,184.68","1,254.85","16,552.71","21,920.06"
11,LIDIA ROSANNA NUÑEZ MELENDEZ,femenino,Encargado de Departamento B Gestión de O,Departamento de Gestión de Operaciones R,Activo,Carrera,"168,463.00","27,780.78","4,834.89","5,121.28","6,823.39","123,902.66"
12,YUDERKA ELIZABETH CASTELLANOS DE JESUS,femenino,Digitador,Sección de Apoyo Contable,Activo,Fijo,"39,696.00",142.42,"1,139.28","1,206.76","6,641.65","30,565.89"
13,ALEJANDRO ANTONIO SUAREZ JOSE,masculino,Auxiliar de Archivo,Gerencia Legal,Activo,Fijo,"27,567.00",0.00,791.17,0.00,"11,574.13","15,201.70"
14,BEATRIZ ABREU DIAZ,femenino,Encargado de Departamento B Consultas Té,Departamento de Consultas Técnicas,Activo,Fijo,"153,149.00","24,607.41","4,395.38","4,655.73","1,231.80","118,258.68"
15,UBALDO TRINIDAD CORDERO,masculino,Gerente Legal,Gerencia Legal,Activo,Carrera,"283,396.00","55,322.42","8,133.47","6,589.14","8,989.47","204,361.50"
16,IDELKI ALTAGRACIA ROSARIO MOREL,femenino,Oficial de Control de Contribuyentes C,Unidad Control de Contribuyentes Villa M,Activo,Fijo,"54,012.00","1,905.60","1,550.14","1,641.96","27,197.12","21,717.18"
17,MILCA FLORENTINO JIMENEZ,femenino,Encargado de Recepción y Custodia de Alm,Sección de Recepción y Custodia de Almac,Activo,Carrera,"108,099.00","14,010.52","3,102.44","3,286.21","16,578.70","71,121.13"
18,ROBERTO ROSARIO MARTINEZ,masculino,Supervisor de Archivo A,Unidad Archivo Herrera,Activo,Fijo,"71,961.00","5,737.47","2,065.28","2,187.61","42,639.49","19,331.15"
19,JUAN AUSBERTO SUAREZ JAVIER,masculino,Analista de Autorización,Sección de Autorización y Habilitación,Activo,Fijo,"81,899.00","7,418.76","2,350.50","2,489.73","20,294.93","49,345.08"
20,CAROLINA MITSUE YAMAMOTO MUÑOZ,femenino,Subdirectora de Facilitación y Servicios,Sub-Dirección Facilitación y Servicios,Activo,Carrera,"363,511.00","75,205.21","10,432.77","6,589.14","12,346.39","258,937.49"
21,DHERYMIN MIRANDA SEVERINO,femenino,Encargado de Recaudación B,Sección Recaudación La Vega,Activo,Carrera,"108,099.00","13,152.79","3,102.44","3,286.21","34,209.16","54,348.40"
22,MARIA DOLORES BRITO PAULINO,femenino,Encargado de Nómina,Sección Nómina,Activo,Carrera,"118,909.00","16,553.31","3,412.69","3,614.83","45,923.82","49,404.35"
23,CELESTE JOSEFINA MONTILLA AMADOR,femenino,Encargado de Departamento B Tesorería,Departamento de Tesorería,Activo,Carrera,"168,463.00","28,209.64","4,834.89","5,121.28","13,514.42","116,782.77"
24,CHRISTIAN RAFAEL LIRIANO OVIEDO,masculino,Encargado de Activo Fijo,Sección Activo Fijo,Activo,Fijo,"98,272.00","11,698.97","2,820.41","2,987.47","58,015.11","22,750.04"
25,JOSE FRANCISCO SANCHEZ TAVERAS,masculino,Coordinador de Control Presupuestario,Sección Control Presupuestario,Activo,Carrera,"118,909.00","16,124.44","3,412.69","3,614.83","62,360.72","33,396.32"
26,STARLIN MELO MATOS,masculino,Auditor Interno,Departamento de Auditoría Interna,Activo,Carrera,"108,099.00","13,152.79","3,102.44","3,286.21","27,301.61","61,255.95"
27,JUANA MARIA ROSADO BELTRE,femenino,Abogado Local A,Administración Local Zona Oriental,Activo,Carrera,"63,071.00","4,064.55","1,810.14","1,917.36","1,225.00","54,053.95"
28,IRENE EVANGELISTA JIMENEZ CARRASCO,femenino,Técnico de Vehículos Motor,Unidad Operaciones Personalizadas Malecó,Activo,Fijo,"46,967.00","1,168.62","1,347.95","1,427.80","17,907.05","25,115.58"
29,SANTIAGO RAFAEL CONTRERAS CERDA,masculino,Oficial de Control de Contribuyentes A,Unidad Control de Contribuyentes San Car,Activo,Fijo,"57,176.00","2,612.14","1,640.95","1,738.15","8,256.86","42,927.90"
30,ELIZABETH POLANCO OLIVERO,femenino,Encargado de Caja A,Unidad Caja San Carlos,Activo,Carrera,"98,945.00","11,857.27","2,839.72","3,007.93","22,409.78","58,830.30"
31,YVONNE MARITZA REYES PEREZ,femenino,Digitador,Unidad Informática San Carlos,Activo,Fijo,"28,588.00",0.00,820.48,0.00,"16,818.00","10,949.52"
32,JOCELIN MARTICH CARO,femenino,Administrador Local A,Administración Local Herrera,Activo,Carrera,"179,694.00","30,422.59","5,157.22","5,462.70","3,472.32","135,179.17"
33,LEOCADIA TAVAREZ,femenino,Coordinador de Auditoría,Departamento de Reconsideración,Activo,Carrera,"139,264.00","20,912.44","3,996.88","4,233.63","22,736.55","87,384.50"
34,MARGARITA LORENZO POLANCO,femenino,Supervisor de Información,Unidad de Información San Carlos,Activo,Fijo,"71,961.00","5,737.47","2,065.28","2,187.61","14,652.36","47,318.28"
35,MARIA YSABEL MERCADO BUENO,femenino,Abogado Local A,Administración Local San Carlos,Activo,Carrera,"63,071.00","3,378.37","1,810.14","1,917.36","17,693.05","38,272.08"
36,MARIA YNMACULADA PEÑA MENA,femenino,Auditor Interno A,Sección Fiscalización Interna Zona Orien,Activo,Fijo,"61,695.00","3,805.61","1,770.65","1,875.53","11,769.13","42,474.08"
37,PAULA NOLASCO DEL ROSARIO,femenino,Encargado de Control de Contribuyente C,Unidad Control de Contribuyentes Villa M,Activo,Carrera,"67,281.00","4,513.70","1,930.96","2,045.34","20,789.74","38,001.26"
38,SANTIAGO EUSEBIO CUESTA REYES,masculino,Digitalizador,Unidad Concesionarios y Distribuidores M,Activo,Fijo,"28,588.00",0.00,820.48,0.00,"22,882.00","4,885.52"
39,SARAH MENDEZ PEREZ,femenino,Secretaria A,Gerencia de Grandes Contribuyentes,Activo,Fijo,"41,278.00",623.02,"1,184.68","1,254.85","6,145.80","32,069.65"
40,WENDY CRISTINA PUESAN,femenino,Auditor Interno GGC,Departamento de Fiscalización Interna GG,Activo,Carrera,"67,864.00","4,623.40","1,947.70","2,063.07","4,466.59","54,763.24"
41,JOSE FRANCISCO CAMACHO DE LA CRUZ,masculino,Verificador,Sección de Autorización y Habilitación,Activo,Fijo,"44,525.00",823.97,"1,277.87","1,353.56","31,211.13","9,858.47"
42,RAMONA GARCIA GARCIA,femenino,Cajero C,Unidad Caja Bonao,Activo,Fijo,"28,588.00",0.00,820.48,0.00,"21,055.31","6,712.21"
43,ARABEL BIENVENIDA ROSARIO GARCIA,femenino,Encargado de Concesionarios y Distrib. M,Unidad Concesionarios y Distribuidores M,Activo,Carrera,"98,945.00","11,857.27","2,839.72","3,007.93","49,154.01","32,086.07"
44,DOMINGA VENTURA MESA,femenino,Encargado de Unidad de VHM A,Unidad Vehículos de Motor Los Próceres,Activo,Fijo,"89,950.00","9,312.56","2,581.57","2,734.48","23,123.39","52,198.00"
45,MARIA LUCIA ESTEVEZ SANCHEZ,femenino,Técnico de Vehículos Motor,Unidad Operaciones Personalizadas Malecó,Activo,Fijo,"46,967.00","1,425.94","1,347.95","1,427.80","24,523.42","18,241.89"
46,MARIBEL HERRERA FLORES DE BAEZ,femenino,Auxiliar de Archivo,Unidad Archivo Vehículos de Motor,Activo,Fijo,"27,567.00",0.00,791.17,0.00,"4,126.32","22,649.51"
47,ONEIDA TERRERO NUÑEZ,femenino,Secretaria A,Departamento de Vehículos de Motor,Activo,Fijo,"41,278.00",623.02,"1,184.68","1,254.85","11,725.46","26,489.99"
48,ROSA IVELISSE TEJEDA DE MARTINEZ,femenino,Encargado Administrativo B,Unidad Administrativa Plaza Luperón,Activo,Fijo,"71,961.00","5,394.38","2,065.28","2,187.61","8,598.00","53,715.73"
49,RUDITH AGUSTINA RAMIREZ VILLAR,femenino,Técnico de Vehículos Motor,Unidad Operaciones Personalizados Plaza,Activo,Fijo,"44,854.00","1,127.72","1,287.31","1,363.56","25,136.84","15,938.57"
50,MARIA VICTORIA ABREU JESUS DE RIJO,femenino,Analista de Seguros y Pensiones,Sección Seguros y Pensiones,Activo,Fijo,"67,905.00","4,974.21","1,948.87","2,064.31","2,169.36","56,748.25"

In [ ]:
DF_Nomina_ImpuestosInternos_Bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3049 entries, 0 to 3048
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      3036 non-null   object
 1   PERSONAL NOMBRADO
OCTUBRE 2025  3035 non-null   object
 2   Unnamed: 2                      3035 non-null   object
 3   Unnamed: 3                      3035 non-null   object
 4   Unnamed: 4                      3035 non-null   object
 5   Unnamed: 5                      3035 non-null   object
 6   Unnamed: 6                      3035 non-null   object
 7   Unnamed: 7                      3035 non-null   object
 8   Unnamed: 8                      3037 non-null   object
 9   Unnamed: 9                      3036 non-null   object
 10  Unnamed: 10                     3035 non-null   object
 11  Unnamed: 11                     3035 non-null   object
dtypes: object(12)
memory usage: 286.0+ KB

In [ ]:
# 1. Crear una copia del DataFrame original para preservarlo intacto
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Bruto.copy()

# 2. Renombrar las columnas según tus especificaciones
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.rename(columns={
    'Unnamed: 0': 'Nombre_Completo',
    'Unnamed: 2': 'Cargo_Funcion',
    'Unnamed: 3': 'Locacion_Departamento',
    'Unnamed: 6': 'Salario_Bruto',
    'Unnamed: 8': 'Descuento_AFP',
    'Unnamed: 7': 'Descuento_ISR',
    'Unnamed: 9': 'Descuento_SFS',
    'Unnamed: 10': 'Otros_Descuentos',
    'Unnamed: 11': 'Salario_Neto'
})

# 3. Seleccionar solo las columnas que necesitamos (eliminar las que no)
columnas_necesarias = [
    'Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento',
    'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
    'Descuento_SFS', 'Otros_Descuentos', 'Salario_Neto'
]

DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta[columnas_necesarias]

# 4. IDENTIFICAR Y ELIMINAR FILAS DE ENCABEZADO/NO DATOS
# Las filas que contienen texto como "Salario Bruto\n(RD$)" son encabezados
# Primero, eliminamos filas donde 'Nombre_Completo' es NaN o está vacío
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.dropna(subset=['Nombre_Completo'])

# Segundo, eliminamos filas que contienen texto de encabezado en la columna 'Nombre_Completo'
textos_encabezado = [
    'Nombre (s) y Apellido (s)',
    'Salario Bruto\n(RD$)',
    'ISR\n(Ley 11-92',
    'Seguridad Social (Ley 87-01)',
    'Otros\nDescuentos',
    'Salario Neto\n(RD$)',
    'Seguro de Pension',
    'Seguro de Salud',
    'Empleado\n(2.87%)',
    'Empleado\n(3.04%)',
    ''
]

# Filtrar para mantener solo filas que NO contienen textos de encabezado
mask = ~DF_Nomina_ImpuestosInternos_Neta['Nombre_Completo'].isin(textos_encabezado)
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta[mask]

# 5. Resetear el índice después de eliminar filas
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.reset_index(drop=True)

# 6. Limpiar y convertir las columnas numéricas
columnas_numericas = ['Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
                      'Descuento_SFS', 'Otros_Descuentos', 'Salario_Neto']

for col in columnas_numericas:
    # Convertir a string, eliminar comas, reemplazar valores vacíos por NaN
    DF_Nomina_ImpuestosInternos_Neta[col] = (
        DF_Nomina_ImpuestosInternos_Neta[col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .replace('nan', np.nan)  # Reemplazar 'nan' string por NaN
        .replace('', np.nan)     # Reemplazar strings vacíos por NaN
    )

    # Convertir a float, forzando errores a NaN
    DF_Nomina_ImpuestosInternos_Neta[col] = pd.to_numeric(
        DF_Nomina_ImpuestosInternos_Neta[col],
        errors='coerce'
    )

# 7. Verificar que tenemos datos numéricos válidos
print("Verificación de conversión numérica:")
for col in columnas_numericas:
    print(f"{col}: {DF_Nomina_ImpuestosInternos_Neta[col].notna().sum()} valores no nulos")

# 8. Calcular la columna Total_Descuentos
DF_Nomina_ImpuestosInternos_Neta['Total_Descuentos'] = (
    DF_Nomina_ImpuestosInternos_Neta['Descuento_AFP'].fillna(0) +
    DF_Nomina_ImpuestosInternos_Neta['Descuento_ISR'].fillna(0) +
    DF_Nomina_ImpuestosInternos_Neta['Descuento_SFS'].fillna(0) +
    DF_Nomina_ImpuestosInternos_Neta['Otros_Descuentos'].fillna(0)
)

# 9. Reordenar las columnas en el orden especificado
column_order = [
    'Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento',
    'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
    'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto'
]

DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta[column_order]

# 10. Convertir los tipos de datos finales
# Columnas de tipo object (categóricas)
DF_Nomina_ImpuestosInternos_Neta['Nombre_Completo'] = DF_Nomina_ImpuestosInternos_Neta['Nombre_Completo'].astype('object')
DF_Nomina_ImpuestosInternos_Neta['Cargo_Funcion'] = DF_Nomina_ImpuestosInternos_Neta['Cargo_Funcion'].astype('object')
DF_Nomina_ImpuestosInternos_Neta['Locacion_Departamento'] = DF_Nomina_ImpuestosInternos_Neta['Locacion_Departamento'].astype('object')

# Columnas de tipo float64 (numéricas) - ya están convertidas
# Solo asegurarnos del tipo
for col in ['Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR',
            'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']:
    if col in DF_Nomina_ImpuestosInternos_Neta.columns:
        DF_Nomina_ImpuestosInternos_Neta[col] = DF_Nomina_ImpuestosInternos_Neta[col].astype('float64')

Verificación de conversión numérica:
Salario_Bruto: 3034 valores no nulos
Descuento_AFP: 3034 valores no nulos
Descuento_ISR: 3034 valores no nulos
Descuento_SFS: 3034 valores no nulos
Otros_Descuentos: 3034 valores no nulos
Salario_Neto: 3034 valores no nulos

In [ ]:
DF_Nomina_ImpuestosInternos_Neta

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EFRAIN EVANGELISTA DIAZ,Encargado de Compras Menores y Directas,Sección Compras Menores y Directas,112438.0,3226.97,15031.16,3418.12,1963.66,23639.91,88798.09
1,MARTIN ALBERTO GOMEZ MARTINEZ,Encargado de Departamento C Protocolo,Departamento de Protocolo,153149.0,4395.38,24178.54,4655.73,10704.18,43933.83,109215.17
2,ROSA ANNETTE SEGURA VARGAS,Secretaria B,Departamento de Seguridad de la Informac,41278.0,1184.68,365.70,1254.85,16552.71,19357.94,21920.06
3,LIDIA ROSANNA NUÑEZ MELENDEZ,Encargado de Departamento B Gestión de O,Departamento de Gestión de Operaciones R,168463.0,4834.89,27780.78,5121.28,6823.39,44560.34,123902.66
4,YUDERKA ELIZABETH CASTELLANOS DE JESUS,Digitador,Sección de Apoyo Contable,39696.0,1139.28,142.42,1206.76,6641.65,9130.11,30565.89
...,...,...,...,...,...,...,...,...,...,...
3030,ABDIEL ARNULFO TAVAREZ JEREZ,Técnico de Información A,Unidad Gestión y Control de Contribuyent,41278.0,1184.68,623.02,1254.85,7175.00,10237.55,31040.45
3031,JOSE MANUEL GORIS MOYA,Técnico de Asistencia,Unidad CAC Malecón Center,46967.0,1347.95,1425.94,1427.80,589.90,4791.59,42175.41
3032,LUISANA ALTAGRACIA DIAZ FRIAS,Técnico de Asistencia,Unidad CAC Malecón Center,46967.0,1347.95,1425.94,1427.80,2708.77,6910.46,40056.54
3033,VIRGILIO DE LOS SANTOS MENDOZA,Gerente Administrativo y Financiero,Gerencia Administrativa y Financiera,257634.0,7394.10,49495.63,6589.14,8075.12,71553.99,186080.01
3034,Raqueline Peña Amaro\nGerente de Recursos Humanos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN

In [ ]:
DF_Nomina_ImpuestosInternos_Neta.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,EFRAIN EVANGELISTA DIAZ,Encargado de Compras Menores y Directas,Sección Compras Menores y Directas,112438.0,3226.97,15031.16,3418.12,1963.66,23639.91,88798.09
1,MARTIN ALBERTO GOMEZ MARTINEZ,Encargado de Departamento C Protocolo,Departamento de Protocolo,153149.0,4395.38,24178.54,4655.73,10704.18,43933.83,109215.17
2,ROSA ANNETTE SEGURA VARGAS,Secretaria B,Departamento de Seguridad de la Informac,41278.0,1184.68,365.70,1254.85,16552.71,19357.94,21920.06
3,LIDIA ROSANNA NUÑEZ MELENDEZ,Encargado de Departamento B Gestión de O,Departamento de Gestión de Operaciones R,168463.0,4834.89,27780.78,5121.28,6823.39,44560.34,123902.66
4,YUDERKA ELIZABETH CASTELLANOS DE JESUS,Digitador,Sección de Apoyo Contable,39696.0,1139.28,142.42,1206.76,6641.65,9130.11,30565.89
5,ALEJANDRO ANTONIO SUAREZ JOSE,Auxiliar de Archivo,Gerencia Legal,27567.0,791.17,0.00,0.00,11574.13,12365.30,15201.70
6,BEATRIZ ABREU DIAZ,Encargado de Departamento B Consultas Té,Departamento de Consultas Técnicas,153149.0,4395.38,24607.41,4655.73,1231.80,34890.32,118258.68
7,UBALDO TRINIDAD CORDERO,Gerente Legal,Gerencia Legal,283396.0,8133.47,55322.42,6589.14,8989.47,79034.50,204361.50
8,IDELKI ALTAGRACIA ROSARIO MOREL,Oficial de Control de Contribuyentes C,Unidad Control de Contribuyentes Villa M,54012.0,1550.14,1905.60,1641.96,27197.12,32294.82,21717.18
9,MILCA FLORENTINO JIMENEZ,Encargado de Recepción y Custodia de Alm,Sección de Recepción y Custodia de Almac,108099.0,3102.44,14010.52,3286.21,16578.70,36977.87,71121.13
10,ROBERTO ROSARIO MARTINEZ,Supervisor de Archivo A,Unidad Archivo Herrera,71961.0,2065.28,5737.47,2187.61,42639.49,52629.85,19331.15
11,JUAN AUSBERTO SUAREZ JAVIER,Analista de Autorización,Sección de Autorización y Habilitación,81899.0,2350.50,7418.76,2489.73,20294.93,32553.92,49345.08
12,CAROLINA MITSUE YAMAMOTO MUÑOZ,Subdirectora de Facilitación y Servicios,Sub-Dirección Facilitación y Servicios,363511.0,10432.77,75205.21,6589.14,12346.39,104573.51,258937.49
13,DHERYMIN MIRANDA SEVERINO,Encargado de Recaudación B,Sección Recaudación La Vega,108099.0,3102.44,13152.79,3286.21,34209.16,53750.60,54348.40
14,MARIA DOLORES BRITO PAULINO,Encargado de Nómina,Sección Nómina,118909.0,3412.69,16553.31,3614.83,45923.82,69504.65,49404.35
15,CELESTE JOSEFINA MONTILLA AMADOR,Encargado de Departamento B Tesorería,Departamento de Tesorería,168463.0,4834.89,28209.64,5121.28,13514.42,51680.23,116782.77
16,CHRISTIAN RAFAEL LIRIANO OVIEDO,Encargado de Activo Fijo,Sección Activo Fijo,98272.0,2820.41,11698.97,2987.47,58015.11,75521.96,22750.04
17,JOSE FRANCISCO SANCHEZ TAVERAS,Coordinador de Control Presupuestario,Sección Control Presupuestario,118909.0,3412.69,16124.44,3614.83,62360.72,85512.68,33396.32
18,STARLIN MELO MATOS,Auditor Interno,Departamento de Auditoría Interna,108099.0,3102.44,13152.79,3286.21,27301.61,46843.05,61255.95
19,JUANA MARIA ROSADO BELTRE,Abogado Local A,Administración Local Zona Oriental,63071.0,1810.14,4064.55,1917.36,1225.00,9017.05,54053.95
20,IRENE EVANGELISTA JIMENEZ CARRASCO,Técnico de Vehículos Motor,Unidad Operaciones Personalizadas Malecó,46967.0,1347.95,1168.62,1427.80,17907.05,21851.42,25115.58
21,SANTIAGO RAFAEL CONTRERAS CERDA,Oficial de Control de Contribuyentes A,Unidad Control de Contribuyentes San Car,57176.0,1640.95,2612.14,1738.15,8256.86,14248.10,42927.90
22,ELIZABETH POLANCO OLIVERO,Encargado de Caja A,Unidad Caja San Carlos,98945.0,2839.72,11857.27,3007.93,22409.78,40114.70,58830.30
23,YVONNE MARITZA REYES PEREZ,Digitador,Unidad Informática San Carlos,28588.0,820.48,0.00,0.00,16818.00,17638.48,10949.52
24,JOCELIN MARTICH CARO,Administrador Local A,Administración Local Herrera,179694.0,5157.22,30422.59,5462.70,3472.32,44514.83,135179.17
25,LEOCADIA TAVAREZ,Coordinador de Auditoría,Departamento de Reconsideración,139264.0,3996.88,20912.44,4233.63,22736.55,51879.50,87384.50
26,MARGARITA LORENZO POLANCO,Supervisor de Información,Unidad de Información San Carlos,71961.0,2065.28,5737.47,2187.61,14652.36,24642.72,47318.28
27,MARIA YSABEL MERCADO BUENO,Abogado Local A,Administración Local San Carlos,63071.0,1810.14,3378.37,1917.36,17693.05,24798.92,38272.08
28,MARIA YNMACULADA PEÑA MENA,Auditor Interno A,Sección Fiscalización Interna Zona Orien,61695.0,1770.65,3805.61,1875.53,11769.13,19220.92,42474.08
29,PAULA NOLASCO DEL ROSARIO,Encargado de Control de Contribuyente C,Unidad Control de Contribuyentes Villa M,67281.0,1930.96,4513.70,2045.34,20789.74,29279.74,38001.26
30,SANTIAGO EUSEBIO CUESTA REYES,Digitalizador,Unidad Concesionarios y Distribuidores M,28588.0,820.48,0.00,0.00,22882.00,23702.48,4885.52
31,SARAH MENDEZ PEREZ,Secretaria A,Gerencia de Grandes Contribuyentes,41278.0,1184.68,623.02,1254.85,6145.80,9208.35,32069.65
32,WENDY CRISTINA PUESAN,Auditor Interno GGC,Departamento de Fiscalización Interna GG,67864.0,1947.70,4623.40,2063.07,4466.59,13100.76,54763.24
33,JOSE FRANCISCO CAMACHO DE LA CRUZ,Verificador,Sección de Autorización y Habilitación,44525.0,1277.87,823.97,1353.56,31211.13,34666.53,9858.47
34,RAMONA GARCIA GARCIA,Cajero C,Unidad Caja Bonao,28588.0,820.48,0.00,0.00,21055.31,21875.79,6712.21
35,ARABEL BIENVENIDA ROSARIO GARCIA,Encargado de Concesionarios y Distrib. M,Unidad Concesionarios y Distribuidores M,98945.0,2839.72,11857.27,3007.93,49154.01,66858.93,32086.07
36,DOMINGA VENTURA MESA,Encargado de Unidad de VHM A,Unidad Vehículos de Motor Los Próceres,89950.0,2581.57,9312.56,2734.48,23123.39,37752.00,52198.00
37,MARIA LUCIA ESTEVEZ SANCHEZ,Técnico de Vehículos Motor,Unidad Operaciones Personalizadas Malecó,46967.0,1347.95,1425.94,1427.80,24523.42,28725.11,18241.89
38,MARIBEL HERRERA FLORES DE BAEZ,Auxiliar de Archivo,Unidad Archivo Vehículos de Motor,27567.0,791.17,0.00,0.00,4126.32,4917.49,22649.51
39,ONEIDA TERRERO NUÑEZ,Secretaria A,Departamento de Vehículos de Motor,41278.0,1184.68,623.02,1254.85,11725.46,14788.01,26489.99
40,ROSA IVELISSE TEJEDA DE MARTINEZ,Encargado Administrativo B,Unidad Administrativa Plaza Luperón,71961.0,2065.28,5394.38,2187.61,8598.00,18245.27,53715.73
41,RUDITH AGUSTINA RAMIREZ VILLAR,Técnico de Vehículos Motor,Unidad Operaciones Personalizados Plaza,44854.0,1287.31,1127.72,1363.56,25136.84,28915.43,15938.57
42,MARIA VICTORIA ABREU JESUS DE RIJO,Analista de Seguros y Pensiones,Sección Seguros y Pensiones,67905.0,1948.87,4974.21,2064.31,2169.36,11156.75,56748.25
43,LUZ MERCEDES NUÑEZ NUÑEZ,Oficial de Notificación,Sección de Notificación,57700.0,1655.99,3053.84,1754.08,3019.65,9483.56,48216.44
44,HERMINIO QUITERIO PLACENCIO,Especialista de Cruces de Información,Sección Planificación de Cruces de Infor,105483.0,3027.36,12966.31,3206.68,29564.15,48764.50,56718.50
45,JUAN CARLOS ANTONIO SANTANA ROSARIO,Coordinador de TI,Departamento de Sistema de apoyo a Recau,142458.0,4088.54,21663.76,4330.72,15766.34,45849.36,96608.64
46,MANUEL SANTANA LOPEZ,Coordinador de TI,Departamento de Sistema de apoyo a Recau,129508.0,3716.88,18188.73,3937.04,6737.78,32580.43,96927.57
47,JULIO ADOLFO MERIÑO FELICIANO,Técnico de Gestión Documental,Departamento Gestión Documental y Archiv,38800.0,1113.56,273.29,1179.52,23059.51,25625.88,13174.12
48,NILDA ALTAGRACIA MEJIA CARRERAS,Oficial de Análisis y Control AT,Sección de Análisis y Control AT,65751.0,1887.05,4225.78,1998.83,13743.44,21855.10,43895.90
49,RAMONA PEÑA DIAZ,Oficial de Análisis y Control AT,Sección de Análisis y Control AT,65751.0,1887.05,4568.87,1998.83,20743.82,29198.57,36552.43
50,VITALINA LUCIA JACKELINE GUZMAN TEJADA,Oficial de Análisis y Control AT,Sección de Análisis y Control AT,65751.0,1887.05,4568.87,1998.83,25048.50,33503.25,32247.75

In [ ]:
DF_Nomina_ImpuestosInternos_Neta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        3035 non-null   object
 1   Cargo_Funcion          3034 non-null   object
 2   Locacion_Departamento  3034 non-null   object
 3   Salario_Bruto          3034 non-null   float64
 4   Descuento_AFP          3034 non-null   float64
 5   Descuento_ISR          3034 non-null   float64
 6   Descuento_SFS          3034 non-null   float64
 7   Otros_Descuentos       3034 non-null   float64
 8   Total_Descuentos       3035 non-null   float64
 9   Salario_Neto           3034 non-null   float64
dtypes: float64(7), object(3)
memory usage: 237.2+ KB

In [ ]:
# Eliminar filas con valores nulos/NaN
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.dropna()

# Convertir strings vacíos o solo espacios a NaN en columnas de texto y eliminarlos
for col in DF_Nomina_ImpuestosInternos_Neta.select_dtypes(include=['object']).columns:
    DF_Nomina_ImpuestosInternos_Neta[col] = DF_Nomina_ImpuestosInternos_Neta[col].replace(r'^\s*$', np.nan, regex=True)

DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.dropna()
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.reset_index(drop=True)

# Eliminar duplicados de Nombre_Completo, manteniendo el mayor Salario_Neto
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.sort_values(
    by=['Nombre_Completo', 'Salario_Neto'],
    ascending=[True, False]
)

DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.drop_duplicates(
    subset=['Nombre_Completo'],
    keep='first'
)

DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.sort_values('Nombre_Completo')
DF_Nomina_ImpuestosInternos_Neta = DF_Nomina_ImpuestosInternos_Neta.reset_index(drop=True)

# Verificar que se eliminaron todos los valores problemáticos
assert DF_Nomina_ImpuestosInternos_Neta.isnull().sum().sum() == 0, "Aún hay valores nulos en el DataFrame"
assert DF_Nomina_ImpuestosInternos_Neta['Nombre_Completo'].duplicated().sum() == 0, "Aún hay nombres duplicados"

print(f"DataFrame limpio: {DF_Nomina_ImpuestosInternos_Neta.shape[0]} filas, {DF_Nomina_ImpuestosInternos_Neta.shape[1]} columnas")

DataFrame limpio: 3033 filas, 10 columnas

/tmp/ipython-input-4284994372.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_Nomina_ImpuestosInternos_Neta[col] = DF_Nomina_ImpuestosInternos_Neta[col].replace(r'^\s*$', np.nan, regex=True)

In [ ]:
DF_Nomina_ImpuestosInternos_Neta

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,AARON MARTINEZ MARTINEZ,Operador de Sistemas,Sección Data Center,85209.0,2445.50,8197.36,2590.35,3740.46,16973.67,68235.33
1,ABDIEL ARNULFO TAVAREZ JEREZ,Técnico de Información A,Unidad Gestión y Control de Contribuyent,41278.0,1184.68,623.02,1254.85,7175.00,10237.55,31040.45
2,ABEL JOSE ASTACIO CASSO,Analista de Operaciones de Regímenes Esp,Sección de Operaciones de Regímenes Espe,81899.0,2350.50,7847.63,2489.73,2333.11,15020.97,66878.03
3,ABIGAIL GUZMAN OGANDO,Gestor de Denuncias,Sub-Dirección Jurídica,85198.0,2445.18,8623.64,2590.02,6880.20,20539.04,64658.96
4,ABIGAIL SANTOS GUZMAN,Cajero CAC,Sección Centro de Asistencia Presencial,28588.0,820.48,0.00,0.00,17172.30,17992.78,10595.22
...,...,...,...,...,...,...,...,...,...,...
3028,ZOILA MARGARITA CONTIN PEREZ,Auditor Externo B,Departamento de Fiscalización Externa GG,94609.0,2715.28,10408.47,2876.11,33430.17,49430.03,45178.97
3029,ZOILA VIOLETA FRANCO BERROA,Secretaria A,Gerencia de Auditoría,41278.0,1184.68,365.70,1254.85,27611.66,30416.89,10861.11
3030,ZORAIDA ALTAGRACIA GARCIA POLANCO,Auditor Interno C,Sección Fiscalización Interna Salcedo,52601.0,1509.65,1963.77,1599.07,11486.25,16558.74,36042.26
3031,ZORAIDA MIGUELINA CUEVAS VASQUEZ,Conserje1,Unidad Administrativo Los Minas,19621.0,563.12,0.00,0.00,4210.10,4773.22,14847.78
3032,ZORANLLY DORLENY MARTINEZ MONTERO,Analista de Atención a Denuncias,Sección de Atención a Denuncias por Frau,81899.0,2350.50,7847.63,2489.73,4525.80,17213.66,64685.34

In [ ]:
DF_Nomina_ImpuestosInternos_Neta.head(51)

,Nombre_Completo,Cargo_Funcion,Locacion_Departamento,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
0,AARON MARTINEZ MARTINEZ,Operador de Sistemas,Sección Data Center,85209.0,2445.50,8197.36,2590.35,3740.46,16973.67,68235.33
1,ABDIEL ARNULFO TAVAREZ JEREZ,Técnico de Información A,Unidad Gestión y Control de Contribuyent,41278.0,1184.68,623.02,1254.85,7175.00,10237.55,31040.45
2,ABEL JOSE ASTACIO CASSO,Analista de Operaciones de Regímenes Esp,Sección de Operaciones de Regímenes Espe,81899.0,2350.50,7847.63,2489.73,2333.11,15020.97,66878.03
3,ABIGAIL GUZMAN OGANDO,Gestor de Denuncias,Sub-Dirección Jurídica,85198.0,2445.18,8623.64,2590.02,6880.20,20539.04,64658.96
4,ABIGAIL SANTOS GUZMAN,Cajero CAC,Sección Centro de Asistencia Presencial,28588.0,820.48,0.00,0.00,17172.30,17992.78,10595.22
5,ABRAHAM TORRES FATULE,Técnico Local B VHM,Unidad Vehículos de Motor Higuey,39818.0,1142.78,416.96,1210.47,2025.00,4795.21,35022.79
6,ABRALIZA ESTHER CAMINERO,Auxiliar Información y Atención al Contr,Sección Recaudación La Romana,27567.0,791.17,0.00,0.00,11753.14,12544.31,15022.69
7,ADA ELISA DE LA CRUZ RINCON,Secretaria A,Administración Local Cotuí,41278.0,1184.68,623.02,1254.85,17966.32,21028.87,20249.13
8,ADA ESTHER DIAZ ALMANZAR,Auditor Interno A,Sección Fiscalización Interna Santiago,67864.0,1947.70,4623.40,2063.07,12558.66,21192.83,46671.17
9,ADA MILCA RAMOS BASTARDO,Oficial de Seguimiento A y T,Sección Seguimiento de AT,65751.0,1887.05,4568.87,1998.83,645.40,9100.15,56650.85
10,ADA NILKA GERONIMO LORA,Analista de Créditos y Compensaciones A,Sección Crédito y Compensaciones,81899.0,2350.50,7847.63,2489.73,3586.64,16274.50,65624.50
11,ADALBERTO MERCEDES REYES,Auditor Externo B,Departamento de Fiscalización Externa GG,94609.0,2715.28,9979.61,2876.11,32227.89,47798.89,46810.11
12,ADALGI PATRICIA DEL ROSARIO NOLBERTO,Cajero de VHM,Unidad CAC Plaza Luperón VHM,46967.0,1347.95,1168.62,1427.80,3019.02,6963.39,40003.61
13,ADALGISA PEREZ SURIEL,Encargado de Educación a Pre-Contribuyen,Sección Educación a Pre-Contribuyentes,98272.0,2820.41,11698.97,2987.47,1751.80,19258.65,79013.35
14,ADALGIZA CASTRO MUÑOZ,Analista de Gestión y Monitoreo de AL,Sección de Gestión y Monitoreo de Admini,81899.0,2350.50,7418.76,2489.73,18071.79,30330.78,51568.22
15,ADALUZ RAMIREZ PUJOLS,Auxiliar Información y Atención al Contr,Sección Personalizados VHM Los Minas,27567.0,791.17,0.00,0.00,5712.72,6503.89,21063.11
16,ADAN ALBERTO BELTRE RAMIREZ,Notificador,Sección de Notificación,36129.0,1036.90,0.00,1098.32,16586.34,18721.56,17407.44
17,ADAN MANUEL SABINO PAULINO,Técnico Local C VHM,Centro de Servicio Local Monte Plata,36755.0,1054.87,0.00,1117.35,2025.00,4197.22,32557.78
18,ADANGELY NUÑEZ FERNANDEZ,Auxiliar de RRHH,Departamento de Gestión de Operaciones R,27567.0,791.17,0.00,0.00,1201.41,1992.58,25574.42
19,ADDERLY VINCENT MONTERO PEREZ,Técnico de Despacho,Sección de Despacho de Mercancias,44923.0,1289.29,1137.46,1365.66,10708.31,14500.72,30422.28
20,ADELAIDA DEL CARMEN ESPINAL UCETA,Auditor Interno A,Sección Fiscalización Interna Abraham Li,63302.0,1816.77,4108.02,1924.38,3018.62,10867.79,52434.21
21,ADELINA DOLORES SANCHEZ RAMIREZ,Coordinador de A&B,Unidad Alimentos & Bebidas,85764.0,2461.43,8756.77,2607.23,25.00,13850.43,71913.57
22,ADER RAMON LUNA VASQUEZ,Encargado de Departamento A Control y Ge,Departamento de Control y Gestión de Adm,190926.0,5479.58,33493.50,5804.15,1407.93,46185.16,144740.84
23,ADILKA MELISSA CRUZ HERNANDEZ,Auditor de Control Previo,Departamento de Control Previo Financier,76679.0,2200.69,6625.30,2331.04,645.40,11802.43,64876.57
24,ADONIS RAMIREZ,Auxiliar de Seguridad,Sección Seguridad Física,33758.0,968.85,0.00,0.00,9927.35,10896.20,22861.80
25,ADONIS LEONARDO RECIO PEREZ,Abogado A Representación Externa,Departamento de Representación Externa,127474.0,3658.50,18568.01,3875.21,8266.60,34368.32,93105.68
26,ADRIAN EUSEBIO MARTE CRUZ,Notificador,Sección de Notificación,36131.0,1036.96,0.00,1098.38,18200.57,20335.91,15795.09
27,ADRIAN JOEL BARETT ANDERSON,Auditor Interno B,Sección Fiscalización Interna La Romana,57177.0,1640.98,2955.42,1738.18,19613.72,25948.30,31228.70
28,ADRIANA VILORIO,Mensajero Interno,Gerencia de Planes Masivos,22269.0,639.12,0.00,0.00,5450.80,6089.92,16179.08
29,ADRIANA MARIA ALMONTE DURAN,Gerente de Planificación Estratégica,Gerencia de Planificación Estratégica,257634.0,7394.10,49495.63,6589.14,16723.29,80202.16,177431.84
30,ADRIANA MARIA HIDALGO RODRIGUEZ,Auditor Interno C,Sección Fiscalización Interna Salcedo,52601.0,1509.65,2221.09,1599.07,3275.28,8605.09,43995.91
31,ADRIANJELY RAFELINA MADERA SUERO,Secretaria A,Gerencia de Cobranza,41278.0,1184.68,623.02,1254.85,13987.79,17050.34,24227.66
32,ADRIANO GUZMAN SEPULVEDA,Oficial de Control de Contribuyentes A,Unidad Control de Contribuyentes Los Pró,57176.0,1640.95,2612.14,1738.15,7337.39,13328.63,43847.37
33,ADRIANO MONTERO RODRIGUEZ,Chofer,Unidad Transportación,25487.0,731.48,0.00,0.00,532.80,1264.28,24222.72
34,ADRIANO DE JESUS SANTANA DE OLEO,Auditor Externo B,Departamento Fiscalización Externa Media,94609.0,2715.28,9979.61,2876.11,7333.12,22904.12,71704.88
35,AGUSTIN JIMENEZ BELEN,Técnico Mecánico Diesel,Sección de Mantenimiento de Equipos,38707.0,1110.89,260.16,1176.69,10468.17,13015.91,25691.09
36,AGUSTIN TAVAREZ GONZALEZ,Mensajero Interno,Unidad Administrativo Zona Oriental,22269.0,639.12,0.00,0.00,1646.13,2285.25,19983.75
37,AGUSTINA DEL RIO RODRIGUEZ,Supervisor de Archivo B,Unidad Archivo Higuey,40841.0,1172.14,304.02,1241.57,3265.52,5983.25,34857.75
38,AIDA MARY CAMACHO PEÑA,Coordinador Educación Tributaria,Departamento de Educación Tributaria,123681.0,3549.64,17246.94,3759.90,3730.59,28287.07,95393.93
39,AILYN SAIMERY PUELLO REYES,Abogado B,Sección Resoluciones,73900.0,2120.93,6102.35,2246.56,24397.21,34867.05,39032.95
40,ALAIM BERNARD BLOISE ESTRELLA,Ingeniero de Sistemas,Sección Data Center,115665.0,3319.59,15361.37,3516.22,3497.26,25694.44,89970.56
41,ALBA ADALGISA MONEGRO BOBADILLA,Técnico de Protocolo,Departamento de Protocolo,59728.0,1714.19,3435.47,1815.73,24858.57,31823.96,27904.04
42,ALBA BELLO ROSA,Abogado Local B,Administración Local San Cristóbal,49415.0,1418.21,1771.44,1502.22,2351.13,7043.00,42372.00
43,ALBA DUNIA ARIAS EGUREN,Analista de Aseguramiento de la Calidad,Sección de Aseguramiento de la Calidad y,67905.0,1948.87,4974.21,2064.31,837.40,9824.79,58080.21
44,ALBA ELIANA RODRIGUEZ SANTIAGO,Secretaria A,Administración Local Mao,41278.0,1184.68,623.02,1254.85,25.00,3087.55,38190.45
45,ALBA LISSETTE PEREZ DILONE,Coordinador de TI,Departamento de Arquitectura Tecnológica,142459.0,4088.57,22092.86,4330.75,12454.27,42966.45,99492.55
46,ALBA MILAGROS DE JESUS FAMILIA,Analista de Aseguramiento de la Calidad,Sección Aseguramiento de la Calidad,85772.0,2461.66,8758.65,2607.47,5025.00,18852.78,66919.22
47,ALBA NELLY RIJO ARECHE,Auxiliar Información y Atención al Contr,Sección Recaudación Higuey,27567.0,791.17,0.00,0.00,2381.80,3172.97,24394.03
48,ALBANIA MADELIS PERDOMO BUSI,Cajero A,Unidad Caja Abraham Lincoln,47280.0,1356.94,1470.11,1437.31,13087.94,17352.30,29927.70
49,ALBENIS ENMANUEL DICKSON FABRE,Tasador AL A,Unidad Tasación Los Próceres,57659.0,1654.81,3046.12,1752.83,2914.60,9368.36,48290.64
50,ALBENNY MASSIEL VALERA SANTANA,Tasador Sede Central,Sección de Procesos Inmobiliarios Masivo,57659.0,1654.81,3046.12,1752.83,4984.91,11438.67,46220.33

In [ ]:
DF_Nomina_ImpuestosInternos_Neta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3033 entries, 0 to 3032
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        3033 non-null   object
 1   Cargo_Funcion          3033 non-null   object
 2   Locacion_Departamento  3033 non-null   object
 3   Salario_Bruto          3033 non-null   float64
 4   Descuento_AFP          3033 non-null   float64
 5   Descuento_ISR          3033 non-null   float64
 6   Descuento_SFS          3033 non-null   float64
 7   Otros_Descuentos       3033 non-null   float64
 8   Total_Descuentos       3033 non-null   float64
 9   Salario_Neto           3033 non-null   float64
dtypes: float64(7), object(3)
memory usage: 237.1+ KB

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

# **CONCATENACION DE LAS 5 NOMINAS YA LIMPIAS**

In [ ]:
# Lista de los DataFrames a concatenar
dataframes = [
    DF_Nomina_Agricultura_NETA,
    DF_Nomina_ObrasPublicas_NETA,
    DF_Nomina_Aduanas_NETA,
    DF_Nomina_MedioAmbiente_NETA,
    DF_Nomina_ImpuestosInternos_Neta
]

# Verificar que todos los DataFrames tengan las mismas columnas
print("Verificando columnas de cada DataFrame:")
for i, df in enumerate(dataframes):
    print(f"DataFrame {i+1}: {df.shape[0]} filas, {df.shape[1]} columnas")
    print(f"Columnas: {list(df.columns)}")
    print("-" * 50)

# Verificar si todas las columnas son iguales
column_sets = [set(df.columns) for df in dataframes]
all_same = all(col_set == column_sets[0] for col_set in column_sets)

if all_same:
    print("✓ Todos los DataFrames tienen las mismas columnas")
else:
    print("✗ Los DataFrames NO tienen las mismas columnas")
    print("\nDiferencias encontradas:")
    for i, col_set in enumerate(column_sets):
        if col_set != column_sets[0]:
            print(f"DataFrame {i+1} difiere del DataFrame 1")
            print(f"Faltan: {column_sets[0] - col_set}")
            print(f"Sobran: {col_set - column_sets[0]}")

    # Si hay diferencias, normalizar las columnas
    common_columns = set.intersection(*column_sets)
    print(f"\nColumnas comunes a todos: {common_columns}")

    # Seleccionar solo las columnas comunes
    dataframes = [df[list(common_columns)] for df in dataframes]

# Concatenar todos los DataFrames
DF_Nomina_Final_Mergiada = pd.concat(dataframes, ignore_index=True)

print("\n" + "="*80)
print("CONCATENACIÓN COMPLETADA")
print("="*80)
print(f"DataFrame inicial: {DF_Nomina_Final_Mergiada.shape[0]} filas, {DF_Nomina_Final_Mergiada.shape[1]} columnas")
print(f"Origen de los datos:")
for i, df in enumerate(dataframes):
    print(f"  - DataFrame {i+1}: {df.shape[0]} filas")

# 1. ELIMINAR FILAS CON VALORES NEGATIVOS
filas_antes_negativos = DF_Nomina_Final_Mergiada.shape[0]
DF_Nomina_Final_Mergiada = DF_Nomina_Final_Mergiada[
    ~(DF_Nomina_Final_Mergiada.select_dtypes(include=[np.number]).lt(0).any(axis=1))
]
filas_despues_negativos = DF_Nomina_Final_Mergiada.shape[0]
negativos_eliminados = filas_antes_negativos - filas_despues_negativos

print(f"\n1. Eliminados {negativos_eliminados} filas con valores negativos")
print(f"   Filas restantes: {filas_despues_negativos}")

# 2. ELIMINAR FILAS CON VALORES EN CERO
filas_antes_cero = DF_Nomina_Final_Mergiada.shape[0]
DF_Nomina_Final_Mergiada = DF_Nomina_Final_Mergiada[
    ~(DF_Nomina_Final_Mergiada.select_dtypes(include=[np.number]).eq(0).any(axis=1))
]
filas_despues_cero = DF_Nomina_Final_Mergiada.shape[0]
ceros_eliminados = filas_antes_cero - filas_despues_cero

print(f"\n2. Eliminados {ceros_eliminados} filas con valores en cero")
print(f"   Filas restantes: {filas_despues_cero}")

# 3. ELIMINAR FILAS CON Salario_Neto MENOR A 14250
filas_antes_salario = DF_Nomina_Final_Mergiada.shape[0]
DF_Nomina_Final_Mergiada = DF_Nomina_Final_Mergiada[
    DF_Nomina_Final_Mergiada['Salario_Neto'] <= 0
]
filas_despues_salario = DF_Nomina_Final_Mergiada.shape[0]
salario_eliminados = filas_antes_salario - filas_despues_salario

print(f"\n3. Eliminados {salario_eliminados} filas con Salario_Neto < 14,250")
print(f"   Filas restantes: {filas_despues_salario}")

# RESULTADO FINAL
print("\n" + "="*80)
print("RESULTADO FINAL")
print("="*80)
print(f"TOTAL FILAS EN DF_Nomina_Final_Mergiada: {DF_Nomina_Final_Mergiada.shape[0]}")
print(f"TOTAL COLUMNAS: {DF_Nomina_Final_Mergiada.shape[1]}")
print(f"TOTAL EMPLEADOS ÚNICOS: {DF_Nomina_Final_Mergiada['Nombre_Completo'].nunique()}")
print("="*80)

Verificando columnas de cada DataFrame:
DataFrame 1: 7794 filas, 10 columnas
Columnas: ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']
--------------------------------------------------
DataFrame 2: 4831 filas, 10 columnas
Columnas: ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']
--------------------------------------------------
DataFrame 3: 3449 filas, 10 columnas
Columnas: ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']
--------------------------------------------------
DataFrame 4: 3107 filas, 10 columnas
Columnas: ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']
--------------------------------------------------
DataFrame 5: 3033 filas, 10 columnas
Columnas: ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']
--------------------------------------------------
✓ Todos los DataFrames tienen las mismas columnas

================================================================================
CONCATENACIÓN COMPLETADA
================================================================================
DataFrame inicial: 22214 filas, 10 columnas
Origen de los datos:
  - DataFrame 1: 7794 filas
  - DataFrame 2: 4831 filas
  - DataFrame 3: 3449 filas
  - DataFrame 4: 3107 filas
  - DataFrame 5: 3033 filas

1. Eliminados 5 filas con valores negativos
   Filas restantes: 22209

2. Eliminados 12162 filas con valores en cero
   Filas restantes: 10047

3. Eliminados 10047 filas con Salario_Neto < 14,250
   Filas restantes: 0

================================================================================
RESULTADO FINAL
================================================================================
TOTAL FILAS EN DF_Nomina_Final_Mergiada: 0
TOTAL COLUMNAS: 10
TOTAL EMPLEADOS ÚNICOS: 0
================================================================================

In [ ]:
DF_Nomina_Final_Mergiada

Empty DataFrame
Columns: [Nombre_Completo, Cargo_Funcion, Locacion_Departamento, Salario_Bruto, Descuento_AFP, Descuento_ISR, Descuento_SFS, Otros_Descuentos, Total_Descuentos, Salario_Neto]
Index: []

In [ ]:
DF_Nomina_Final_Mergiada.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nombre_Completo        0 non-null      object
 1   Cargo_Funcion          0 non-null      object
 2   Locacion_Departamento  0 non-null      object
 3   Salario_Bruto          0 non-null      float64
 4   Descuento_AFP          0 non-null      float64
 5   Descuento_ISR          0 non-null      float64
 6   Descuento_SFS          0 non-null      float64
 7   Otros_Descuentos       0 non-null      float64
 8   Total_Descuentos       0 non-null      float64
 9   Salario_Neto           0 non-null      float64
dtypes: float64(7), object(3)
memory usage: 0.0+ bytes

-
-
-
-
-
-
-
-
-
-
-
-
-
# **EDA POST-FE**

In [ ]:
DF_Nomina_Final_Mergiada.describe()

,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(f"Índices duplicados en original: {DF_Nomina_Final_Mergiada.index.duplicated().sum()}")
print(f"Índices únicos en original: {DF_Nomina_Final_Mergiada.index.nunique()}")

Índices duplicados en original: 0
Índices únicos en original: 0

In [ ]:
Test = DF_Nomina_Final_Mergiada
Test.describe()

,Salario_Bruto,Descuento_AFP,Descuento_ISR,Descuento_SFS,Otros_Descuentos,Total_Descuentos,Salario_Neto
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN

-
-
-
-
-
-
-
-
-
-
-
-
-
# **ESTANDARIZACION/NORMALIZACION**  *y ENCODING*

Primero hacemos el encoding:

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# 1. Crear el encoder y aplicar encoding
encoder = OneHotEncoder()
columnas_categoricas = ['Cargo_Funcion', 'Locacion_Departamento']
df_cat = DF_Nomina_Final_Mergiada[columnas_categoricas]
df_cat_encoded = pd.DataFrame(
    encoder.fit_transform(df_cat).toarray(),
    columns=encoder.get_feature_names_out(columnas_categoricas)
)

# 2. RESETEAR ÍNDICES para evitar duplicación
df_cat_encoded = df_cat_encoded.reset_index(drop=True)
df_numerico = DF_Nomina_Final_Mergiada.drop(columns=columnas_categoricas).reset_index(drop=True)

# 3. Combinar con el DataFrame original
DF_Nomina_Encoded = pd.concat([df_numerico, df_cat_encoded], axis=1)

print(f"   Encoding completado CORRECTAMENTE")
print(f"   Filas en original: {DF_Nomina_Final_Mergiada.shape[0]}")
print(f"   Filas en encoded: {DF_Nomina_Encoded.shape[0]}")
print(f"   Columnas en original: {DF_Nomina_Final_Mergiada.shape[1]}")
print(f"   Columnas en encoded: {DF_Nomina_Encoded.shape[1]}")
print(f"\n   Número de filas debería ser IGUAL: {DF_Nomina_Final_Mergiada.shape[0] == DF_Nomina_Encoded.shape[0]}")

>>> Estado del DataFrame antes del encoding:
Shape: (0, 10)
Columnas: ['Nombre_Completo', 'Cargo_Funcion', 'Locacion_Departamento', 'Salario_Bruto', 'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS', 'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto']

ValueError: ERROR: DF_Nomina_Final_Mergiada está vacío. No hay datos para codificar.

In [ ]:
df_cat_encoded

In [ ]:
df_cat_encoded.head(51)

-
-
-

Ahora hacemos la normalizacion / estandarizacion:

In [ ]:
from sklearn.preprocessing import StandardScaler

# 1. Identificar columnas numéricas (EXCLUYENDO Salario_Bruto que es el target)
columnas_numericas_a_normalizar = [
    'Descuento_AFP', 'Descuento_ISR', 'Descuento_SFS',
    'Otros_Descuentos', 'Total_Descuentos', 'Salario_Neto'
]

# 2. Aplicar StandardScaler
scaler = StandardScaler()
df_num_normalizar = DF_Nomina_Final_Mergiada[columnas_numericas_a_normalizar]

df_num_scaled = pd.DataFrame(
    scaler.fit_transform(df_num_normalizar),
    columns=columnas_numericas_a_normalizar  # Mantener mismos nombres
)

print(f"✅ df_num_scaled creado")
print(f"   Columnas: {df_num_scaled.shape[1]} (solo numéricas normalizadas)")
print(f"   Filas: {df_num_scaled.shape[0]}")
print(f"   Se mantienen 8,498 filas: {df_num_scaled.shape[0] == 8498}")

# 3. Mostrar las columnas
print(f"\nColumnas en df_num_scaled:")
for col in df_num_scaled.columns:
    print(f"  • {col}")

# 4. Mostrar primeras filas
print("\nPrimeras 3 filas de df_num_scaled:")
print(df_num_scaled.head(3))

# 5. Mostrar estadísticas (deberían tener media ~0, std ~1)
print("\nEstadísticas (media ~0, std ~1):")
print(df_num_scaled.describe().loc[['mean', 'std']])

In [ ]:
df_num_scaled

In [ ]:
df_num_scaled.head(51)

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

# **SPLITTING X and Y**

aqui voy a juntar las columnas encoded (categoricas) y las columnas normalizadas (numericas).

In [ ]:
# Combinar las columnas encoded y scaled para crear X
X = pd.concat([df_cat_encoded, df_num_scaled], axis=1)

In [ ]:
X

-
-
-

In [ ]:
# Crear y (variable objetivo)
y = DF_Nomina_Final_Mergiada['Salario_Bruto']

In [ ]:
y

-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-

# ENTRENAMIENTO DE MODELOS

In [ ]:
X

-
-
---
-

-

# **division de la data para ENTRANIENTO y luego TESTEO/EVALUACION**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

-
-
-
-
-

# Entrenamiento de modelo/algoritmo #1:
**ORDINARY LEAST SQUARES REGRESSION**

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

# 1. Crear y entrenar el modelo OLS (LinearRegression usa OLS por defecto)
model_ols = LinearRegression()
model_ols.fit(X_train, y_train)

# 2. Hacer predicciones
y_predict = model_ols.predict(X_test)

# 3. Crear DataFrame con resultados
df_results = pd.concat([
    y_test.reset_index(drop=True),
    pd.Series(y_predict, name="Predicted_Salario_Bruto")
], axis=1)

# 4. Calcular métricas
mae = mean_absolute_error(y_test, y_predict)
rmse = root_mean_squared_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)


print(f"Modelo entrenado con {len(X_train)} muestras")
print(f"Evaluado con {len(X_test)} muestras")

print("\n MÉTRICAS DE EVALUACIÓN:")
print(f"• Mean Absolute Error (MAE): {mae:,.2f}")
print(f"• Root Mean Squared Error (RMSE): {rmse:,.2f}")
print(f"• R² Score: {r2:.4f}")

print("\n")
print(f"• MAE: Error promedio de {mae:,.2f} pesos por predicción")
print(f"• RMSE: {rmse:,.2f} pesos (penaliza errores grandes)")
print(f"• R²: {r2:.2%} de la varianza en Salario_Bruto es explicada por el modelo")

In [ ]:
df_results